import type { Spec, SignalRule } from '../../platform-api';
import './backtest-builder.css';
import { useEffect, useState } from 'react';
import { request } from '../../platform-api';

type Props = { spec: Spec; onChange: (spec: Spec) => void; features: {id:string;category:string}[]; step:number };

export default function BacktestSettings({spec,onChange,features,step}:Props) {
  const [preview,setPreview]=useState<{rows:number;start:string;end:string;features:{id:string;valid_rows:number}[];note:string}|null>(null);
  const [previewError,setPreviewError]=useState('');
  const [preparing,setPreparing]=useState(false);
  useEffect(()=>{
    if(step!==1)return;
    let cancelled=false;
    setPreview(null);setPreviewError('');setPreparing(true);
    request<NonNullable<typeof preview>>('/backtest-preview','POST',spec).then(value=>{if(!cancelled)setPreview(value);}).catch(error=>{if(!cancelled)setPreviewError(String(error));}).finally(()=>{if(!cancelled)setPreparing(false);});
    return ()=>{cancelled=true;};
  },[step,spec.dataset_id,spec.timeframe,spec.period?.start,spec.period?.end]);
  const period=spec.period??{start:null,end:null,test_start:null};
  const rules=spec.signal_rules??{long:[],short:[]};
  function updateRule(side:'long'|'short', index:number, patch:Partial<SignalRule>) {
    onChange({...spec,signal_rules:{...rules,[side]:rules[side].map((rule,i)=>i===index?{...rule,...patch}:rule)}});
  }
  if(step===0) return <fieldset><legend>Veri tarih aralığı (UTC)</legend><div className="form-grid">{(['start','end'] as const).map(key=><label key={key}>{key==='start'?'Başlangıç':'Bitiş (dahil)'}<input type="date" value={period[key]??''} onChange={e=>onChange({...spec,period:{...period,[key]:e.target.value||null}})}/></label>)}</div><p className="footnote">Boş bırakılan sınır için tüm veri kullanılır. İndikatörlerin ısınması için başlangıçtan önceki barlar kullanılabilir.</p></fieldset>;
  if(step===1) return <fieldset><legend>Görsel sinyal filtreleri</legend>{preparing&&<p role="status">İndikatörler önceden hesaplanıyor…</p>}{previewError&&<p role="alert">{previewError}</p>}{preview&&<details><summary>{preview.features.length} hazır özellik · {preview.rows} bar · {preview.start.slice(0,10)} → {preview.end.slice(0,10)}</summary><p>{preview.note}</p>{preview.features.map(f=><p key={f.id}>{f.id}: {f.valid_rows} geçerli bar</p>)}</details>}<p className="footnote">Modelin long/short tahmini yalnızca ilgili koşulların tümü sağlanınca işlem sinyaline dönüşür. Boş liste filtre uygulamaz. RSI_14: 0–100; EMA: fiyata göre oran; ATR: fiyat oranı; Bollinger konumu: alt bant 0, üst bant 1. Kesişim bir önceki barla karşılaştırılır.</p>{(['long','short'] as const).map(side=><div key={side}><h3>{side==='long'?'Long giriş koşulları':'Short giriş koşulları'}</h3>{rules[side].map((rule,index)=><div className="form-grid" key={index}><label>İndikatör<select value={rule.feature} onChange={e=>updateRule(side,index,{feature:e.target.value})}>{features.map(f=><option key={f.id} value={f.id}>{f.id}</option>)}</select></label><label>Koşul<select value={rule.operator} onChange={e=>updateRule(side,index,{operator:e.target.value as SignalRule['operator']})}><option value="gt">Büyüktür</option><option value="lt">Küçüktür</option><option value="cross_above">Yukarı keser</option><option value="cross_below">Aşağı keser</option></select></label><label>Eşik<input type="number" step="any" required value={rule.value} onChange={e=>updateRule(side,index,{value:Number(e.target.value)})}/></label><button type="button" className="secondary" onClick={()=>onChange({...spec,signal_rules:{...rules,[side]:rules[side].filter((_,i)=>i!==index)}})}>Koşulu kaldır</button></div>)}<button type="button" className="secondary" disabled={!features.length||rules[side].length>=10} onClick={()=>onChange({...spec,signal_rules:{...rules,[side]:[...rules[side],{feature:'rsi_14',operator:side==='long'?'gt':'lt',value:50}]}})}>+ {side} koşulu</button></div>)}</fieldset>;
  if(step===3) return <fieldset><legend>Arama uzayı</legend><label><input type="checkbox" checked={spec.optimization.hyperparameters} onChange={e=>onChange({...spec,optimization:{...spec.optimization,hyperparameters:e.target.checked}})}/> Model parametrelerini optimize et</label><label>Sinyal eşiği adayları (baz puan, virgülle ayırın)<input defaultValue={(spec.optimization.thresholds_bps??[0,.25,.5,1,2]).join(', ')} onBlur={e=>{const values=e.target.value.split(',').map(s=>Number(s.trim()));if(values.length&&values.length<=20&&values.every(v=>Number.isFinite(v)&&v>=0)) {e.target.setCustomValidity('');onChange({...spec,optimization:{...spec.optimization,thresholds_bps:values}});}else{e.target.setCustomValidity('0 veya daha büyük en fazla 20 sayı girin.');e.target.reportValidity();}}}/></label><p className="footnote">Grid: seçili tüm özelliklerle model × üç parametre profili × eşik kombinasyonları. Random/genetik: ayrıca özellik alt kümeleri. Toplam en fazla 128 aday. Final test optimizasyona kapalıdır.</p></fieldset>;
  if(step===4) return <fieldset><legend>Final test ayrımı</legend><label>Validation oranı (%)<input type="number" min="5" max="40" step="1" required value={Math.round((spec.validation.validation_ratio??.15)*100)} onChange={e=>onChange({...spec,validation:{...spec.validation,validation_ratio:Number(e.target.value)/100}})}/></label><label>Final test başlangıç tarihi (isteğe bağlı)<input type="date" value={period.test_start??''} onChange={e=>onChange({...spec,period:{...period,test_start:e.target.value||null}})}/></label><p className="footnote">Tarih seçilirse final test bu tarihte başlar. Öncesi geliştirme verisidir; holdout eğitim/doğrulama oranı kendi içinde uygulanır. Walk-forward, rolling ve anchored yöntemleri birden fazla eğitim/doğrulama penceresi kullanır. Final model geliştirme verisiyle yeniden eğitilir.</p></fieldset>;
  if(step===5) return <fieldset><legend>Backtest seçimleri</legend><p>{period.start??'Veri başlangıcı'} → {period.end??'Veri sonu'} · Test: {period.test_start??`%${Math.round((1-spec.validation.train_ratio-(spec.validation.validation_ratio??.15))*100)}`}</p><p>Arama: {spec.optimization.algorithm} · Long filtre: {rules.long.length} · Short filtre: {rules.short.length}</p>{([...rules.long,...rules.short]).map((r,i)=><p key={i}>{r.feature} {r.operator} {r.value}</p>)}</fieldset>;
  return null;
}
