import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowDownToLine, ArrowRight, ArrowUpRight, BookOpen, Check, ChevronDown, CircleHelp, Clock3, Database, FlaskConical, Layers3, LayoutDashboard, Loader2, Moon, Play, Plus, Radio, Settings2, Square, Sun, Terminal, Upload, X, Zap } from 'lucide-react';
import { Area, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Config, Dataset, Job, Result } from './types';
import ResearchPlatform from './ResearchPlatform';
import './workspace.css';

const fmt = (v:number, digits=2) => new Intl.NumberFormat('tr-TR',{maximumFractionDigits:digits,minimumFractionDigits:digits}).format(v);
const pct = (v:number) => `${v>0?'+':''}${fmt(v*100)}%`;
const date = (s:string) => new Date(s).toLocaleDateString('tr-TR',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'});
const colors = ['#55dfb0','#8b91f3','#efb66c','#62b5ef','#e78fbe'];
const statusLabel:Record<string,string> = {queued:'Sırada',running:'Çalışıyor',completed:'Tamamlandı',failed:'Başarısız',cancelled:'İptal edildi'};
async function api<T>(url:string, options?:RequestInit):Promise<T>{
  const response = await fetch(`/api${url}`,options);
  if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(typeof body.detail==='string'?body.detail:'İstek tamamlanamadı. Parametreleri kontrol edin.');}
  return response.json();
}

function Performance({result,mode,theme}:{result:Result;mode:string;theme:'dark'|'light'}){
  const step=Math.max(1,Math.ceil(result.curve.length/600));
  const points=result.curve.filter((_,i)=>i%step===0||i===result.curve.length-1);
  const data=points;
  return <div className="chart" role="img" aria-label={mode==='equity'?'Test dönemi sermaye eğrisi ve al tut karşılaştırması':'Test dönemi maksimum sermayeden düşüş grafiği'}>
    <ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{top:18,right:8,left:0,bottom:4}}>
      <defs><linearGradient id="equityFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#50dfad" stopOpacity={0.19}/><stop offset="100%" stopColor="#50dfad" stopOpacity={0}/></linearGradient></defs>
      <CartesianGrid stroke={theme==='light'?'#dce3ea':'#242b35'} strokeDasharray="3 5" vertical={false}/>
      <XAxis dataKey="timestamp" tickFormatter={s=>new Date(s).toLocaleDateString('tr-TR',{month:'short',day:'2-digit',timeZone:'UTC'})} minTickGap={65} tick={{fill:theme==='light'?'#64748b':'#748092',fontSize:11}} axisLine={false} tickLine={false}/>
      <YAxis domain={mode==='equity'?['auto','auto']:['auto',0]} width={66} tickFormatter={v=>mode==='equity'?`$${fmt(v,0)}`:`${fmt(v,1)}%`} tick={{fill:theme==='light'?'#64748b':'#748092',fontSize:11}} axisLine={false} tickLine={false}/>
      <Tooltip contentStyle={{background:theme==='light'?'#ffffff':'#161d27',border:`1px solid ${theme==='light'?'#d5dde5':'#354153'}`,borderRadius:10,fontSize:12,color:theme==='light'?'#172033':'#e8edf4'}} labelFormatter={s=>date(String(s))} formatter={(v,name)=>[mode==='equity'?`$${fmt(Number(v))}`:`${fmt(Number(v))}%`,name]}/>
      {mode==='equity'?<><Line dataKey="benchmark" name="Al & tut" stroke="#858fa5" dot={false} strokeDasharray="5 5" strokeWidth={1.5}/><Area dataKey="equity" name="HMM Ensemble" type="monotone" stroke="#55dfb0" fill="url(#equityFill)" strokeWidth={2.3} isAnimationActive={false}/></>:<Area dataKey="drawdown" name="Düşüş" stroke="#ef8f93" fill="#ef8f9320" isAnimationActive={false}/>}
    </ComposedChart></ResponsiveContainer>
  </div>;
}

function App(){
  const [datasets,setDatasets]=useState<Dataset[]>([]),[history,setHistory]=useState<Job[]>([]),[job,setJob]=useState<Job|null>(null);
  const [page,setPage]=useState('platform'),[modal,setModal]=useState(false),[workspaceModal,setWorkspaceModal]=useState(false),[workspaceDraft,setWorkspaceDraft]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[online,setOnline]=useState(false),[chartMode,setChartMode]=useState('equity');
  const [platformNew,setPlatformNew]=useState(0);
  const [theme,setTheme]=useState<'dark'|'light'>(()=>localStorage.getItem('regimelab.theme')==='light'?'light':'dark');
  const [project,setProject]=useState<{notebooks:{name:string;cells:number}[];scope:string}|null>(null);
  const [config,setConfig]=useState<Config>({dataset_id:'demo',interval:'native',train_ratio:0.65,states:3,cost_bps:0.5,capital:10000});
  const [workspaceName,setWorkspaceName]=useState(()=>localStorage.getItem('regimelab.workspace_name')||'EUR/USD Araştırması');
  const uploadRef=useRef<HTMLInputElement>(null),dialogRef=useRef<HTMLDialogElement>(null),workspaceDialogRef=useRef<HTMLDialogElement>(null);
  const result=job?.result,active=!!job&&['running','queued'].includes(job.status);
  const selected=datasets.find(d=>d.id===config.dataset_id)||datasets[0];
  async function refresh(){const [ds,hs,pr]=await Promise.all([api<Dataset[]>('/datasets'),api<Job[]>('/runs'),api<{notebooks:{name:string;cells:number}[];scope:string}>('/project')]);setDatasets(ds);setHistory(hs);setProject(pr);setOnline(true);return hs;}
  useEffect(()=>{let alive=true;refresh().then(async hs=>{if(hs.length){const j=await api<Job>(`/runs/${hs[0].id}`);if(alive)setJob(j);}}).catch(e=>{setError(e.message);setOnline(false);});return()=>{alive=false;};},[]);
  useEffect(()=>{if(!active||!job)return;let alive=true;const id=job.id;const timer=setInterval(()=>{api<Job>(`/runs/${id}`).then(j=>{if(!alive)return;setJob(j);setOnline(true);if(!['running','queued'].includes(j.status))refresh().catch(()=>{});}).catch(e=>{if(alive){setError(e.message);setOnline(false);}});},1000);return()=>{alive=false;clearInterval(timer);};},[job?.id,active]);
  useEffect(()=>{const d=dialogRef.current;if(modal&&!d?.open)d?.showModal();if(!modal&&d?.open)d.close();},[modal]);
  useEffect(()=>{const d=workspaceDialogRef.current;if(workspaceModal&&!d?.open)d?.showModal();if(!workspaceModal&&d?.open)d.close();},[workspaceModal]);
  useEffect(()=>{
    document.documentElement.dataset.theme=theme;
    document.querySelector('meta[name="theme-color"]')?.setAttribute('content',theme==='light'?'#f7f9fc':'#0c1017');
    localStorage.setItem('regimelab.theme',theme);
  },[theme]);
  async function run(){setBusy(true);setError('');try{const j=await api<Job>('/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(config)});setJob(j);setModal(false);setPage('overview');setOnline(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function upload(file?:File){if(!file)return;setUploading(true);setError('');try{const form=new FormData();form.append('file',file);const ds=await api<Dataset>('/datasets',{method:'POST',body:form});setDatasets(prev=>[...prev,ds]);setConfig(prev=>({...prev,dataset_id:ds.id}));setPage('data');}catch(e){setError((e as Error).message);}finally{setUploading(false);if(uploadRef.current)uploadRef.current.value='';}}
  async function openRun(id:string){try{setJob(await api<Job>(`/runs/${id}`));setPage('overview');}catch(e){setError((e as Error).message);}}
  function renameWorkspace(){
    setWorkspaceDraft(workspaceName);
    setWorkspaceModal(true);
  }
  function saveWorkspaceName(){
    const next=workspaceDraft.trim();
    if(!next)return;
    const name=next.slice(0,60);
    localStorage.setItem('regimelab.workspace_name',name);
    setWorkspaceName(name);
    setWorkspaceModal(false);
  }
  const nav=[['platform','Deney platformu',FlaskConical],['overview','HMM çalışma alanı',LayoutDashboard],['data','Veri merkezi',Database],['models','Uzman modeller',Layers3],['regimes','Piyasa rejimleri',Activity],['history','Önceki deneyler',Clock3]] as const;
  const heading:Record<string,string>={platform:'Araştırma ve deney platformu',overview:'Araştırma çalışma alanı',data:'Veri merkezi',models:'Uzman modeller',regimes:'Piyasa rejimleri',history:'Deney geçmişi',method:'Proje ve metodoloji'};
  return <div className="app-shell">
    <aside className="sidebar">
      <a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('overview');}}><span className="brand-mark"><Activity size={23}/></span><span>regime<span className="brand-light">lab</span><small>QUANT RESEARCH WORKSPACE</small></span></a>
      <button type="button" className="workspace" onClick={renameWorkspace} title="Çalışma alanı adını değiştir"><span className="workspace-icon">FX</span><div>{workspaceName}<small>Yerel çalışma alanı · adı değiştir</small></div><ChevronDown size={14}/></button>
      <span className="nav-label">ÇALIŞMA ALANI</span>
      <nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'nav-item selected':'nav-item'} onClick={()=>setPage(id)}><Icon size={18}/>{label}{id==='overview'&&<span className="nav-dot"/>}</button>)}</nav>
      <div className="sidebar-note"><div className="tiny-icon"><FlaskConical size={17}/></div><strong>Fikirden deneye.</strong><p>Uzmanları eğit, rejimleri keşfet, sonuçları karşılaştır.</p><button onClick={()=>setPage('method')}>Projenin yapısı <ArrowUpRight size={14}/></button></div>
      <div className="sidebar-bottom"><button className={`nav-item ${page==='method'?'selected':''}`} onClick={()=>setPage('method')}><BookOpen size={18}/>Metodoloji</button><div className="user"><span>Q</span><div>Quant Research<small>Python + React · v1.0</small></div><span className="connection-dot"/></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb">Çalışma alanı <span>/</span><b>{heading[page]}</b></div><div className="topbar-right"><span className={online?'connection':'connection offline'}><i/>{online?'Python bağlı':'Bağlantı yok'}</span><span className="local-label">LOCAL</span><button className="icon-button theme-toggle" title={theme==='dark'?'Beyaz temaya geç':'Koyu temaya geç'} aria-label={theme==='dark'?'Beyaz temaya geç':'Koyu temaya geç'} onClick={()=>setTheme(current=>current==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button><button className="icon-button" title="Metodoloji" aria-label="Metodolojiyi aç" onClick={()=>setPage('method')}><CircleHelp size={18}/></button></div></header>
    <main>
      <div className="page-heading"><div><div className="eyebrow">EUR/USD <span>·</span> REJİM ODAKLI MODELLEME</div><h1>{page==='overview'?'Piyasayı anla. Modelini geliştir.':heading[page]}</h1><p>{page==='overview'?'Veriden sinyale, tüm araştırma sürecin tek bir çalışma alanında.':'EUR/USD araştırmanızın verilerini, modellerini ve sonuçlarını inceleyin.'}</p></div><button className="primary" onClick={()=>{setError('');if(page==='platform')setPlatformNew(n=>n+1);else setModal(true);}} disabled={page!=='platform'&&active}><Plus size={17}/>Yeni deney</button></div>
      {error&&<div className="alert" role="alert"><span>{error}</span><button aria-label="Hata mesajını kapat" onClick={()=>setError('')}><X size={16}/></button></div>}
      <input ref={uploadRef} type="file" accept=".csv,text/csv" hidden onChange={e=>upload(e.target.files?.[0])}/>
      {page==='platform'&&<ResearchPlatform newRequest={platformNew}/>}
      {page==='overview'&&<>
        <div className="dataset-strip"><div className="pair-icon">€<span>$</span></div><div className="pair-title"><strong>EUR / USD</strong><span>Euro / ABD Doları</span></div><span className="divider"/><div className="strip-detail"><small>VERİ KAYNAĞI</small><b>{job?job.dataset_name:selected?.name||'Yükleniyor…'}</b></div><div className="strip-detail hide-small"><small>DENEY</small><b>{job?`#${job.id.slice(0,8)}`:'Henüz başlatılmadı'}</b></div><span className={`badge ${job?.demo??selected?.demo?'amber':''}`}>{(job?.demo??selected?.demo)?'Sentetik veri':'Yüklenen CSV'}</span></div>
        <div className="metrics-grid">{[
          {label:'TOPLAM GETİRİ',value:result?pct(result.metrics.return):'—',sub:'İşlem maliyetleri dahil',kind:result&&result.metrics.return>=0?'positive':'',icon:ArrowUpRight},
          {label:'SHARPE ORANI',value:result?fmt(result.metrics.sharpe):'—',sub:'Test dönemi · risksiz oran = 0',kind:'',icon:Activity},
          {label:'MAKSİMUM DÜŞÜŞ',value:result?pct(result.metrics.max_drawdown):'—',sub:'Sermayenin zirveden kaybı',kind:'negative',icon:Layers3},
          {label:'POZİSYON DEĞİŞİMİ',value:result?fmt(result.metrics.position_changes,0):'—',sub:result?`${fmt(result.metrics.active_bars,0)} aktif bar`:'Açılış ve yön değişimleri',kind:'',icon:Zap}
        ].map(m=><div className="metric-card" key={m.label}><div className="metric-label">{m.label}<m.icon size={15}/></div><div className={`metric-value ${m.kind}`}>{m.value}</div><span className="metric-sub">{m.sub}</span></div>)}</div>
        <div className="dashboard-grid"><section className="panel performance"><div className="panel-heading"><div><h2>Sermaye performansı <span className="mini-badge">TEST</span></h2><p>{result?`${date(result.split.test_start)} — ${date(result.split.test_end)}`:'Ayrılmış test dönemindeki strateji performansı'}</p></div><div className="segmented"><button className={chartMode==='equity'?'chosen':''} onClick={()=>setChartMode('equity')}>Sermaye</button><button className={chartMode==='drawdown'?'chosen':''} onClick={()=>setChartMode('drawdown')}>Düşüş</button></div></div>
        {result?<><div className="chart-legend"><span><i style={{background:colors[0]}}/>HMM Ensemble</span><span><i style={{background:'#858fa5'}}/>Al & tut</span><b>USD</b></div><Performance result={result} mode={chartMode} theme={theme}/></>:<div className="chart-empty"><div className="empty-graph"><Activity size={60} strokeWidth={1}/></div><strong>{active?'Deney hesaplanıyor':'İlk deneyin burada başlayacak'}</strong><p>{active?'Eğitim tamamlandığında gerçek sonuçlar bu alanda görünecek.':'Örnek veriyle akışı keşfet veya kendi EUR/USD verini yükle.'}</p><button className="secondary" onClick={()=>setModal(true)} disabled={active}><Play size={14}/>Deneyi yapılandır</button></div>}
        <div className="panel-footer"><span className="dot green"/>{job?.demo??true?'Sentetik veriyle araştırma · canlı piyasa verisi değildir':'Yüklenen veri üzerinde hesaplandı'}<span className="right">{result?`${fmt(result.split.test,0)} test barı`:'Sonuç bekleniyor'}</span></div></section>
        <section className="panel pipeline"><div className="panel-heading"><div><h2>Deney akışı</h2><p>Tekrarlanabilir araştırma süreci</p></div><Settings2 size={17} className="muted"/></div><div className="pipeline-steps">{[['Veri hazırlığı','OHLC doğrulama ve özellikler',15],['Uzman eğitimi','Trend · Momentum · Volatilite',65],['Rejim analizi','Gaussian HMM · nedensel çıkarım',80],['Backtest ve rapor','Maliyetler dahil test dönemi',100]].map(([title,sub,threshold],i)=>{const done=job&&job.progress>=Number(threshold),current=active&&!done&&(i===0||job.progress>=Number([0,15,65,80][i]));return <div className={`pipeline-step ${done?'done':''} ${current?'current':''}`} key={title}><span className="step-circle">{done?<Check size={14}/>:current?<Loader2 className="spin" size={14}/>:String(i+1).padStart(2,'0')}</span><div><b>{title}</b><small>{sub}</small></div></div>;})}</div><button className="run-button" disabled={active||busy||!online} onClick={()=>setModal(true)}>{active?<Loader2 size={16} className="spin"/>:<Play size={16}/>} {active?'Deney çalışıyor':'Deney çalıştır'}<ArrowRight size={16}/></button><p className="pipeline-note">CPU üzerinde çalışır · sabit rastgelelik tohumu</p></section></div>
        <div className="lower-grid"><section className="panel"><div className="panel-heading"><div><h2>Strateji karşılaştırması</h2><p>Aynı test dönemi, aynı maliyet varsayımı</p></div><button className="text-button" disabled={!result} onClick={()=>job&&window.open(`/api/runs/${job.id}/export`,'_blank')}><ArrowDownToLine size={15}/>CSV</button></div>{result?<Comparison result={result}/>:<div className="small-empty"><Layers3 size={25}/><span>Ensemble ve uzman sonuçları deneyden sonra listelenecek.</span></div>}</section><section className="panel"><div className="panel-heading"><div><h2>Rejim dağılımı</h2><p>Test dönemindeki HMM durumları</p></div><Radio size={17} className="muted"/></div>{result?<div className="regime-summary"><div className="distribution">{result.regimes.map(r=><span key={r.id} style={{width:`${r.share*100}%`,background:colors[r.id]}} title={`S${r.id}: ${fmt(r.share*100,1)}%`}/>)}</div>{result.regimes.map(r=><div className="regime-line" key={r.id}><span><i className="dot" style={{background:colors[r.id]}}/>Durum {r.id}</span><small>{fmt(r.bars,0)} bar</small><b>{fmt(r.share*100,1)}%</b></div>)}<button className="text-button regime-link" onClick={()=>setPage('regimes')}>Rejim detaylarını incele <ArrowRight size={14}/></button></div>:<div className="small-empty"><Activity size={25}/><span>Rejimler eğitim verisinden öğrenilecek.</span></div>}</section></div>
        {job&&<section className="panel log-panel"><div className="panel-heading"><div className="log-title"><Terminal size={17}/><h2>Çalıştırma günlüğü</h2><span className={`badge ${job.status==='failed'?'amber':''}`}>{statusLabel[job.status]}</span></div><div className="log-actions"><span>{job.progress}%</span>{active&&<button className="text-button" disabled={job.cancel_requested} onClick={async()=>{try{await api(`/runs/${job.id}/cancel`,{method:'POST'});setJob({...job,cancel_requested:true});}catch(e){setError((e as Error).message);}}}><Square size={12}/>{job.cancel_requested?'İptal bekleniyor':'İptal et'}</button>}</div></div><div className="progress-track"><span style={{width:`${job.progress}%`}}/></div><div className="logs" aria-live="polite">{job.logs.slice(-5).map((log,i)=><div key={i}><time>{new Date(log.time).toLocaleTimeString('tr-TR')}</time><span>{log.message}</span></div>)}{['failed','cancelled'].includes(job.status)&&<div className="negative">{job.message}</div>}</div></section>}
      </>}
      {page==='data'&&<><div className="upload-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!uploading)upload(e.dataTransfer.files[0]);}}><Upload size={30}/><h2>EUR/USD verini çalışma alanına ekle</h2><p>CSV dosyanı sürükle veya bilgisayarından seç. 400–200.000 satır, en fazla 25 MB.</p><div><button className="primary" disabled={uploading} onClick={()=>uploadRef.current?.click()}>{uploading?<Loader2 size={16} className="spin"/>:<Upload size={16}/>}CSV yükle</button><a className="secondary" href="/api/sample.csv" download>OHLC örneği</a><a className="secondary" href="/api/sample-external.csv" download>Laglı veri örneği</a></div><code>Timestamp, Open, High, Low, Close[, macro__name, macro__name__available_at]</code><p className="footnote">Haricî seriler için <code>macro__</code>, <code>cross_asset__</code>, <code>fx__</code> veya <code>rates__</code> öneki; yayın zamanı için ilgili <code>__available_at</code> UTC sütunu kullanılır.</p></div><section className="panel"><div className="panel-heading"><div><h2>Veri setleri</h2><p>Bir veri seti seçerek önizlemesini inceleyin.</p></div><span className="badge">{datasets.length} veri seti</span></div><div className="table-wrap"><table><thead><tr><th>Veri seti</th><th>Satır</th><th>Başlangıç</th><th>Bitiş</th><th>Kaynak</th><th/></tr></thead><tbody>{datasets.map(d=><tr key={d.id}><td><Database size={14}/>{d.name}</td><td>{fmt(d.rows,0)}</td><td>{date(d.start)}</td><td>{date(d.end)}</td><td><span className={`badge ${d.demo?'amber':''}`}>{d.demo?'Sentetik':'CSV'}</span></td><td><button className="text-button" onClick={()=>setConfig({...config,dataset_id:d.id})}>{config.dataset_id===d.id?<><Check size={14}/>Seçili</>:'Seç'}</button></td></tr>)}</tbody></table></div></section>{selected&&<section className="panel spacing-top"><div className="panel-heading"><div><h2>Veri önizlemesi</h2><p>{selected.name} · son 8 bar · UTC</p></div><button className="secondary" onClick={()=>setModal(true)} disabled={active}>Bu veriyle deney <ArrowRight size={14}/></button></div><div className="table-wrap"><table><thead><tr><th>Zaman</th>{selected.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{selected.preview.map((r,i)=><tr key={i}><td>{String(r.timestamp).replace('T',' ').slice(0,16)}</td>{selected.columns.map(c=><td key={c}>{fmt(Number(r[c]),5)}</td>)}</tr>)}</tbody></table></div></section>}</>}
      {page==='models'&&(result?<><div className="expert-grid">{result.experts.map((expert,i)=><section className="panel expert-card" key={expert.name}><span className="expert-icon" style={{color:colors[i],background:`${colors[i]}15`}}><Layers3 size={24}/></span><span className="eyebrow">UZMAN 0{i+1}</span><h2>{expert.name}</h2><p>{expert.family}</p><div className="expert-stat"><b>{expert.features.length}</b><span>teknik özellik</span></div><div className="feature-tags">{expert.features.map(f=><span key={f}>{f}</span>)}</div></section>)}</div><section className="panel spacing-top"><div className="panel-heading"><div><h2>Uzman ve ensemble sonuçları</h2><p>Ağırlıklar rejim bazında doğrulama hatasından hesaplanır.</p></div></div><Comparison result={result}/></section></>:<Empty onStart={()=>setModal(true)} title="Uzmanlar ilk deneyle hazır olacak" text="Trend için Ridge, momentum için Random Forest ve volatilite için Histogram Gradient Boosting eğitilir."/>)}
      {page==='regimes'&&(result?<><div className="regime-cards">{result.regimes.map(r=><section className="panel regime-card" key={r.id}><span className="badge" style={{color:colors[r.id]}}>DURUM {r.id}</span><h2>{fmt(r.share*100,1)}<small>%</small></h2><p>{fmt(r.bars,0)} test barı</p><div className="regime-stat"><span>Durumda kalma olasılığı</span><b>{fmt(r.persistence*100,1)}%</b></div><div className="regime-stat"><span>Ortalama hedef getirisi</span><b>{fmt(r.mean_return_bps)} bp</b></div><h3>Uzman ağırlıkları</h3>{r.weights.map((w,i)=><div className="weight-row" key={i}><div><span>{result.experts[i].name}</span><b>{fmt(w*100,1)}%</b></div><div className="weight-track"><span style={{width:`${w*100}%`,background:colors[i]}}/></div></div>)}</section>)}</div><section className="panel spacing-top"><div className="panel-heading"><div><h2>Rejim geçiş matrisi</h2><p>Satır: mevcut durum · sütun: sonraki durum · eğitimde öğrenilen olasılıklar</p></div></div><div className="table-wrap"><table className="transition-table"><thead><tr><th>Geçiş</th>{result.regimes.map(r=><th key={r.id}>S{r.id}</th>)}</tr></thead><tbody>{result.transition.map((row,i)=><tr key={i}><th>S{i}</th>{row.map((v,j)=><td key={j} style={{background:`rgba(85,223,176,${v*.23})`}}>{fmt(v*100,1)}%</td>)}</tr>)}</tbody></table></div></section><p className="footnote">Durum numaraları yükseliş/düşüş etiketi değildir. Test getirileri yalnızca betimleyici amaçla gösterilir.</p></>:<Empty onStart={()=>setModal(true)} title="Piyasa rejimlerini keşfet" text="Gaussian HMM, getiri, volatilite ve momentum üzerinden 2–5 durum öğrenir."/>)}
      {page==='history'&&<section className="panel"><div className="panel-heading"><div><h2>Kaydedilen deneyler</h2><p>Sonuçlar yerel diskte saklanır; önceki çalıştırmaları yeniden açabilirsiniz.</p></div><span className="badge">{history.length} deney</span></div>{history.length?<div className="table-wrap"><table><thead><tr><th>Deney</th><th>Veri seti</th><th>Tarih</th><th>Durum</th><th>Rejim</th><th/></tr></thead><tbody>{history.map(h=><tr key={h.id}><td>#{h.id.slice(0,8)}</td><td>{h.dataset_name}</td><td>{date(h.created_at)}</td><td><span className="badge">{statusLabel[h.status]}</span></td><td>{h.config.states} durum</td><td><button className="text-button" disabled={active&&h.id!==job?.id} onClick={()=>openRun(h.id)}>İncele <ArrowUpRight size={14}/></button></td></tr>)}</tbody></table></div>:<div className="small-empty"><Clock3 size={26}/><span>Henüz kaydedilmiş deney yok.</span></div>}</section>}
      {page==='method'&&<div className="method-layout"><section className="panel prose"><span className="eyebrow">PROJENİN AMACI</span><h2>Rejim farkındalığıyla EUR/USD modelleme</h2><p>Bu proje, döviz fiyatlarını tahmin eden uzman modellerin farklı piyasa koşullarında nasıl birleştirilebileceğini araştırıyor. Arayüz, veri hazırlığından test raporuna kadar tekrarlanabilir bir OHLC deney akışı sunuyor.</p><h3>Mevcut notebooklar</h3>{project?.notebooks.map(n=><div className="notebook" key={n.name}><BookOpen size={20}/><div><b>{n.name}</b><p>{n.name.startsWith('optimus')?'TFT mimarileri, teknik göstergeler ve fiyat tahmini denemeleri.':'Makro ve teori uzmanları, ensemble havuzları, HMM rejimleri ve tez raporları.'}</p></div><span>{n.cells} hücre</span></div>)}<h3>Bu arayüzde çalışan akış</h3><p>{project?.scope}</p><ol>{(result?.notes||['Teknik özellikler yalnızca mevcut ve geçmiş barlardan üretilir.','Üç uzman ve HMM yalnızca eğitim verisinde öğrenir. HMM durumları ileri yönlü filtreyle çıkarılır.','Rejim ağırlıkları ve işlem eşiği doğrulamada seçilir. Test verisi seçimde kullanılmaz.','Sinyal kapanışta oluşturulur, sonraki açılışta uygulanır ve bir açılıştan diğerine getiri hesaplanır.','Bu sürüm TFT, FRED/Dukascopy veri çekimi ve MAIN_14 makro havuzlarının birebir yürütücüsü değildir.']).map(n=><li key={n}>{n}</li>)}</ol><h3>Notebooklarla ilgili bulgular</h3><p>Klasörde yalnızca iki notebook vardı; harici CSV dosyaları ve eğitilmiş ağırlıklar yoktu. Notebooklarda yinelenen deney hücreleri, harici servis bağımlılıkları ve farklı model tanımları bulunuyor. Kaynak dosyalar korunmuştur; bu arayüz kendi düzenli Python hattını çalıştırır.</p><p>Sharpe hesabı sıfır risksiz oran ve yılda 252 işlem günü varsayar. Kazanma oranı aktif barlar üzerinden hesaplanır; pozisyon değişimi tamamlanmış işlem sayısı değildir.</p><div className="inline-note">Sentetik veri yalnızca uygulama akışını denemek içindir. Gösterilen sonuçlar, seçili çalıştırmanın hesaplanan test sonuçlarıdır.</div></section><section className="panel method-side"><h2>Deney protokolü</h2><div><small>Hedef</small><b>Sonraki açılıştan bir sonraki açılışa</b></div><div><small>Doğrulama</small><b>Kronolojik · %15</b></div><div><small>Sınır aralığı</small><b>Her sınırda 2 bar</b></div><div><small>Rejim çıkarımı</small><b>Nedensel ileri filtre</b></div><div><small>Rastgelelik tohumu</small><b>42</b></div><div><small>İşlem maliyeti</small><b>Tek yön · baz puan</b></div></section></div>}
      <footer className="footer"><span><Activity size={13}/>REGIME LAB <i/> Araştırma için tasarlandı.</span><span>Yerel hesaplama · Veriler bu bilgisayarda saklanır</span></footer>
    </main></div>
    <dialog ref={workspaceDialogRef} onCancel={()=>setWorkspaceModal(false)} onClick={e=>{if(e.target===workspaceDialogRef.current)setWorkspaceModal(false);}}><form onSubmit={e=>{e.preventDefault();saveWorkspaceName();}}><div className="dialog-heading"><span className="workspace-icon">FX</span><button type="button" className="icon-button" aria-label="Pencereyi kapat" onClick={()=>setWorkspaceModal(false)}><X size={20}/></button></div><h2>Yerel çalışma alanı</h2><p className="dialog-description">Bu ad yalnızca bu tarayıcıdaki yerel görünümü tanımlar; veri ve deney kayıtları bilgisayarınızda kalır.</p><label>Çalışma alanı adı<input autoFocus required maxLength={60} value={workspaceDraft} onChange={e=>setWorkspaceDraft(e.target.value)} /></label><button className="primary full-width" type="submit">Kaydet</button></form></dialog>
    <dialog ref={dialogRef} onCancel={()=>setModal(false)} onClick={e=>{if(e.target===dialogRef.current)setModal(false);}}><form onSubmit={e=>{e.preventDefault();run();}}><div className="dialog-heading"><span className="expert-icon"><FlaskConical size={22}/></span><button type="button" className="icon-button" aria-label="Pencereyi kapat" onClick={()=>setModal(false)}><X size={20}/></button></div><h2>Yeni deney oluştur</h2><p className="dialog-description">Verini ve araştırma parametrelerini seç. Sonuçlar otomatik kaydedilir.</p>{error&&<div className="alert" role="alert">{error}</div>}
    <label>Veri seti<select value={config.dataset_id} onChange={e=>setConfig({...config,dataset_id:e.target.value})}>{datasets.map(d=><option key={d.id} value={d.id}>{d.name}{d.demo?' (sentetik)':''}</option>)}</select></label>
    <div className="form-grid"><label>Bar periyodu<select value={config.interval} onChange={e=>setConfig({...config,interval:e.target.value})}><option value="native">Kaynak periyodu</option><option value="10min">10 dakika</option><option value="1h">1 saat</option><option value="4h">4 saat</option><option value="1D">1 gün</option></select></label><label>HMM durum sayısı<select value={config.states} onChange={e=>setConfig({...config,states:Number(e.target.value)})}>{[2,3,4,5].map(n=><option key={n} value={n}>{n} durum</option>)}</select></label><label>Başlangıç sermayesi (USD)<input required type="number" min="100" max="100000000" value={config.capital} onChange={e=>setConfig({...config,capital:Number(e.target.value)})}/></label><label>Tek yön maliyeti (bp)<input required type="number" min="0" max="20" step="0.1" value={config.cost_bps} onChange={e=>setConfig({...config,cost_bps:Number(e.target.value)})}/></label></div>
    <label className="slider-label">Eğitim oranı <b>{fmt(config.train_ratio*100,0)}%</b><input type="range" min="50" max="75" step="5" value={Math.round(config.train_ratio*100)} onChange={e=>setConfig({...config,train_ratio:Number(e.target.value)/100})}/></label><div className="split-bar"><span style={{width:`${config.train_ratio*100}%`}}/><span style={{width:'15%'}}/><span style={{flex:1}}/></div><div className="split-labels"><span>Eğitim %{fmt(config.train_ratio*100,0)}</span><span>Doğrulama %15</span><span>Test %{fmt((.85-config.train_ratio)*100,0)}</span></div>
    <div className="inline-note"><Clock3 size={16}/><span>3 uzman + Gaussian HMM · CPU eğitimi. 1 bp = %0,01. Seçilen maliyet giriş ve çıkışlarda uygulanır.</span></div><button className="primary full-width" disabled={busy||active||!datasets.length} type="submit">{busy?<Loader2 size={16} className="spin"/>:<Play size={16}/>}Eğitimi ve backtesti başlat</button></form></dialog>
  </div>;
}

function Comparison({result}:{result:Result}){return <div className="table-wrap"><table><thead><tr><th>STRATEJİ</th><th>GETİRİ</th><th>SHARPE</th><th>MAKS. DÜŞÜŞ</th></tr></thead><tbody>{result.comparison.map((m,i)=><tr key={m.name} className={i===0?'highlight-row':''}><td><span className="model-dot" style={{background:colors[i%colors.length]}}/>{m.name}{i===0&&<span className="table-tag">ENSEMBLE</span>}</td><td className={m.return>=0?'positive':'negative'}>{pct(m.return)}</td><td>{fmt(m.sharpe)}</td><td className="muted">{pct(m.max_drawdown)}</td></tr>)}</tbody></table></div>;}
function Empty({onStart,title,text}:{onStart:()=>void;title:string;text:string}){return <section className="panel big-empty"><FlaskConical size={40}/><h2>{title}</h2><p>{text}</p><button className="primary" onClick={onStart}><Play size={16}/>Deney oluştur</button></section>;}
export default App;
