import {useEffect,useRef,useState} from 'react';
import {ArrowDownToLine,ArrowRight,Check,Copy,FlaskConical,GitCompareArrows,LockKeyhole,Play,RefreshCw,Search,Square,X} from 'lucide-react';
import {CartesianGrid,ComposedChart,Line,ResponsiveContainer,Tooltip,XAxis,YAxis,Scatter,ScatterChart} from 'recharts';
import {request,download,defaultSpec,headers,terminal} from './platform-api';
import type {Spec,Experiment,Result,Comparison,Event,Generation} from './platform-api';
import type {Dataset} from './types';
import './platform.css';

const fmt=(v:number|undefined,d=2)=>v===undefined?'—':new Intl.NumberFormat('tr-TR',{maximumFractionDigits:d}).format(v);
const percent=(v:number)=>`${fmt(v*100)}%`;
const palette=['#55dfb0','#8b91f3','#efb66c','#62b5ef','#e78fbe'];
const stateLabel:Record<string,string>={DRAFT:'Taslak',QUEUED:'Sırada',DATA_PREPARATION:'Veri hazırlanıyor',FEATURE_ENGINEERING:'Özellikler',TRAINING:'Eğitim',OPTIMIZING:'Optimizasyon',VALIDATING:'Doğrulama',TESTING:'Final test',BACKTESTING:'Backtest',ANALYZING:'Analiz',COMPLETED:'Tamamlandı',FAILED:'Başarısız',CANCELLED:'İptal',TIMEOUT:'Süre sınırı'};
const initial=()=>structuredClone(defaultSpec);

export default function ResearchPlatform({newRequest}:{newRequest:number}){
  const [experiments,setExperiments]=useState<Experiment[]>([]),[selected,setSelected]=useState<Experiment|null>(null),[result,setResult]=useState<Result|null>(null);
  const [datasets,setDatasets]=useState<Dataset[]>([]),[features,setFeatures]=useState<{id:string;category:string}[]>([]),[models,setModels]=useState<{id:string;name:string}[]>([]);
  const [families,setFamilies]=useState<{id:string;name:string;description:string;requires?:string}[]>([]);
  const [capabilities,setCapabilities]=useState<{unavailable:{name:string;status:string}[];policy:Record<string,number>}|null>(null);
  const [view,setView]=useState('registry'),[detailTab,setDetailTab]=useState('overview'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState('');
  const [checked,setChecked]=useState<string[]>([]),[comparison,setComparison]=useState<Comparison|null>(null),[logs,setLogs]=useState<Event[]>([]),[generations,setGenerations]=useState<Generation[]>([]);
  const [wizard,setWizard]=useState(false),[step,setStep]=useState(0),[spec,setSpec]=useState<Spec>(initial),[editing,setEditing]=useState<string|null>(null),[tokenInput,setTokenInput]=useState('');
  const [activity,setActivity]=useState<{id:number;source:string;operation:string;entity_id:string;created_at:string}[]>([]);
  const dialog=useRef<HTMLDialogElement>(null),selectionRef=useRef<string|null>(null);
  const active=selected&&selected.status!=='DRAFT'&&!terminal(selected.status);
  const fail=(e:unknown)=>setError(e instanceof Error?e.message:String(e));
  async function refresh(){setExperiments(await request<Experiment[]>('/experiments'));}
  async function load(){try{const [es,ds,fs,ms,cs,fm]=await Promise.all([request<Experiment[]>('/experiments'),request<Dataset[]>('/datasets'),request<{id:string;category:string}[]>('/features'),request<{id:string;name:string}[]>('/models'),request<typeof capabilities>('/capabilities'),request<typeof families>('/feature-families')]);setExperiments(es);setDatasets(ds);setFeatures(fs);setModels(ms);setCapabilities(cs);setFamilies(fm);setError('');}catch(e){fail(e);}}
  useEffect(()=>{load();},[]);
  useEffect(()=>{if(wizard)request<{id:string;category:string}[]>(`/features?dataset_id=${encodeURIComponent(spec.dataset_id)}`).then(setFeatures).catch(fail);},[wizard,spec.dataset_id]);
  useEffect(()=>{if(newRequest){setSpec(initial());setEditing(null);setStep(0);setWizard(true);}},[newRequest]);
  useEffect(()=>{if(wizard&&!dialog.current?.open)dialog.current?.showModal();if(!wizard&&dialog.current?.open)dialog.current.close();},[wizard]);
  async function open(id:string){selectionRef.current=id;setResult(null);try{const e=await request<Experiment>(`/experiments/${id}`);if(selectionRef.current!==id)return;setSelected(e);setView('detail');const records=await request<Event[]>(`/experiments/${id}/logs`);if(selectionRef.current!==id)return;setLogs(records);setGenerations(records.filter(r=>r.type==='optimization.generation.completed').map(r=>r.payload as unknown as Generation));if(e.status==='COMPLETED'){const r=await request<Result>(`/experiments/${id}/result`);if(selectionRef.current===id)setResult(r);}}catch(e){fail(e);}}
  useEffect(()=>{
    if(!selected||!active)return;
    const id=selected.id,controller=new AbortController();let cursor=0;
    async function listen(){
      try{
        const response=await fetch(`/api/v1/experiments/${id}/events?after=${cursor}`,{headers:headers(),signal:controller.signal});
        if(!response.ok||!response.body)throw new Error('Canlı ilerleme bağlantısı kurulamadı. Yenile düğmesini kullanın.');
        const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';
        while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let pos;
          while((pos=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,pos);buffer=buffer.slice(pos+2);const line=block.split('\n').find(l=>l.startsWith('data: '));
            if(line&&!block.includes('event: done')){const event=JSON.parse(line.slice(6)) as Event;cursor=event.id;
              setLogs(prev=>prev.some(e=>e.id===event.id)?prev:[...prev,event]);
              if(event.type==='optimization.generation.completed')setGenerations(prev=>prev.some(g=>g.generation===(event.payload as unknown as Generation).generation)?prev:[...prev,event.payload as unknown as Generation]);
              if(event.type==='experiment.status.changed'&&terminal(String(event.payload.status))){await open(id);await refresh();return;}
              if(event.type==='experiment.status.changed')setSelected(prev=>prev&&prev.id===id?{...prev,status:String(event.payload.status),run:prev.run?{...prev.run,status:String(event.payload.status),progress:Number(event.payload.progress||prev.run.progress),message:String(event.payload.message||prev.run.message)}:null}:prev);
            }
          }
        }
        if(!controller.signal.aborted){await open(id);await refresh();}
      }catch(e){if(!controller.signal.aborted)fail(e);}
    }
    listen();return()=>controller.abort();
  },[selected?.id,!!active]);
  async function perform(work:()=>Promise<void>){setBusy(true);setError('');try{await work();}catch(e){fail(e);}finally{setBusy(false);}}
  function newExperiment(){setEditing(null);setSpec(initial());setStep(0);setWizard(true);}
  async function create(){await perform(async()=>{const e=await request<Experiment>(editing?`/experiments/${editing}`:'/experiments',editing?'PATCH':'POST',spec);setWizard(false);await refresh();await open(e.id);});}
  async function run(){if(!selected)return;await perform(async()=>{await request(`/experiments/${selected.id}/run`,'POST',undefined,{'Idempotency-Key':`web-${selected.id}`});await open(selected.id);await refresh();});}
  async function clone(){if(!selected)return;await perform(async()=>{const e=await request<Experiment>(`/experiments/${selected.id}/clone`,'POST',{name:selected.name.slice(0,100)+' · klon'});await refresh();await open(e.id);setEditing(e.id);setSpec(e.specification);setStep(0);setWizard(true);});}
  async function compare(){await perform(async()=>{setComparison(await request<Comparison>('/experiments/compare','POST',{experiment_ids:checked}));setView('compare');});}
  const shown=experiments.filter(e=>(!statusFilter||e.status===statusFilter)&&(e.name+e.code+e.specification.models.join(' ')).toLowerCase().includes(query.toLowerCase()));
  const steps=['Veri','Özellikler','Modeller','Optimizasyon','Doğrulama / maliyet','Gözden geçir'];
  const stepValid=step===0?!!spec.name.trim()&&!!spec.dataset_id:step===2?spec.models.length>0:step===3?spec.optimization.min_features<=spec.optimization.max_features&&spec.optimization.population*spec.optimization.generations<=128:true;
  return <div className="research-platform">
    <div className="research-toolbar"><div className="research-tabs">{[['registry','Deneyler'],['compare','Karşılaştırma'],['catalog','Yöntemler / API'],['activity','İşlem kaydı']].map(([id,name])=><button className={view===id?'chosen':''} key={id} onClick={()=>{setView(id);if(id==='activity')request<typeof activity>('/activity').then(setActivity).catch(fail);}}>{name}</button>)}</div><button className="text-button" onClick={()=>{load();if(selected)open(selected.id);}}><RefreshCw size={14}/>Yenile</button></div>
    {error&&<div className="alert" role="alert">{error}<button aria-label="Kapat" onClick={()=>setError('')}><X size={14}/></button></div>}
    {!capabilities&&<section className="panel research-auth"><p>Sunucu API anahtarıyla yapılandırıldıysa anahtarı bu oturum için girin.</p><label>API anahtarı<input type="password" value={tokenInput} onChange={e=>setTokenInput(e.target.value)}/></label><button className="secondary" onClick={()=>{sessionStorage.setItem('regimelab-token',tokenInput);load();}}>Bağlan</button></section>}
    {view==='registry'&&<><div className="research-summary"><div><span>DENEY KAYDI</span><b>{experiments.length}</b></div><div><span>TAMAMLANAN</span><b>{experiments.filter(e=>e.status==='COMPLETED').length}</b></div><div><span>AKTİF / KUYRUK</span><b>{experiments.filter(e=>e.status!=='DRAFT'&&!terminal(e.status)).length}</b></div><div><LockKeyhole size={19}/><span>TEST ERİŞİMİ</span><strong>Aday seçildikten sonra</strong></div></div><section className="panel"><div className="panel-heading"><div><h2>Deney kayıt defteri</h2><p>Snapshot, specification ve sonuçlar aynı deney kimliği altında saklanır.</p></div><button className="secondary" onClick={newExperiment}>Yeni deney <ArrowRight size={14}/></button></div><div className="research-filters"><label><Search size={14}/><input placeholder="Ad, kod veya model ara" aria-label="Deney ara" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Duruma göre filtrele" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Tüm durumlar</option>{Object.entries(stateLabel).map(([s,l])=><option value={s} key={s}>{l}</option>)}</select><button className="secondary" disabled={checked.length<2||busy} onClick={compare}><GitCompareArrows size={14}/>Karşılaştır ({checked.length}/5)</button></div><div className="table-wrap"><table><thead><tr><th/><th>Deney / köken</th><th>Modeller</th><th>Optimizer</th><th>Test Sharpe</th><th>Durum</th><th/></tr></thead><tbody>{shown.map(e=><tr key={e.id}><td><input type="checkbox" aria-label={`${e.code} karşılaştırmaya ekle`} checked={checked.includes(e.id)} disabled={e.status!=='COMPLETED'||(!checked.includes(e.id)&&checked.length>=5)} onChange={()=>setChecked(prev=>prev.includes(e.id)?prev.filter(id=>id!==e.id):[...prev,e.id])}/></td><td><b>{e.name}</b><small className="table-subline">{e.code}{e.parent_id?' ← '+(experiments.find(p=>p.id===e.parent_id)?.code||e.parent_id.slice(0,8)):''}</small></td><td>{e.specification.models.join(', ')}</td><td>{e.specification.optimization.algorithm}</td><td>{fmt(e.run?.metrics?.sharpe)}</td><td><span className="badge">{stateLabel[e.status]||e.status}</span></td><td><button className="text-button" onClick={()=>open(e.id)}>İncele <ArrowRight size={13}/></button></td></tr>)}</tbody></table></div>{!shown.length&&<div className="small-empty"><FlaskConical size={30}/><span>Yeni bir deney oluşturarak başlayın. Önceki sürümün sonuçları Deney geçmişi ekranında korunur.</span></div>}</section></>}
    {view==='detail'&&selected&&<>
      <section className="panel experiment-banner"><div><span className="eyebrow">{selected.code}</span><h2>{selected.name}</h2><p>{selected.snapshot.details.name} · {fmt(selected.snapshot.details.rows,0)} bar · {selected.specification.models.join(' + ')}</p><code>SHA256 {selected.snapshot.sha256.slice(0,20)}…</code></div><div className="experiment-actions"><span className="badge">{stateLabel[selected.status]||selected.status}</span><button className="secondary" disabled={busy} onClick={clone}><Copy size={14}/>Klonla</button>{selected.status==='DRAFT'?<><button className="secondary" onClick={()=>{setEditing(selected.id);setSpec(selected.specification);setStep(0);setWizard(true);}}>Düzenle</button><button className="primary" onClick={run} disabled={busy}><Play size={14}/>Çalıştır</button></>:active?<button className="secondary" disabled={busy} onClick={()=>perform(async()=>{await request(`/experiments/${selected.id}/cancel`,'POST');await open(selected.id);})}><Square size={13}/>İptal et</button>:null}</div></section>
      <div className="test-policy"><LockKeyhole size={14}/><b>Optimizer test erişimi: kapalı</b><span>Test öncesi aday sabitlenir · aynı deney ikinci kez çalıştırılamaz</span></div>
      <div className="research-tabs detail-tabs">{[['overview','Sonuç'],['optimization','Optimization Lab'],['features','Feature Lab'],['validation','Doğrulama'],['regimes','Rejimler'],['artifacts','Artifact / snapshot'],['logs','Günlük']].map(([id,l])=><button key={id} className={detailTab===id?'chosen':''} onClick={()=>setDetailTab(id)}>{l}</button>)}</div>
      {active&&<div className="running-bar"><span>{selected.run?.message}</span><b>{generations.length?`Nesil ${generations[generations.length-1].generation}/${selected.specification.optimization.generations}`:`${selected.run?.progress||0}%`}</b><div className="progress-track"><span style={{width:`${selected.run?.progress||0}%`}}/></div></div>}
      {selected.run&&['FAILED','CANCELLED','TIMEOUT'].includes(selected.status)&&<div className="alert">{selected.run.message}</div>}
      {detailTab==='overview'&&(result?<><div className="metrics-grid">{[['Getiri',percent(result.metrics.return)],['Sharpe',fmt(result.metrics.sharpe)],['Maksimum düşüş',percent(result.metrics.max_drawdown)],['Sortino',fmt(result.metrics.sortino)]].map(([l,v])=><div className="metric-card" key={l}><div className="metric-label">{l}</div><div className="metric-value">{v}</div></div>)}</div><section className="panel"><div className="panel-heading"><div><h2>{result.selected_model} · {result.selected_features.length} özellik</h2><p>Validation Sharpe {fmt(result.validation_metrics.sharpe)} → Test Sharpe {fmt(result.metrics.sharpe)} · fark {fmt(result.validation_test_sharpe_delta)}</p></div><button className="text-button" onClick={()=>download(`/experiments/${selected.id}/export`,`${selected.code}.csv`).catch(fail)}><ArrowDownToLine size={14}/>CSV</button></div><EquityOverlay items={[{experiment:selected,result}]}/></section>{result.warnings.map(w=><div className="inline-note" key={w}>{w}</div>)}</>:<section className="panel big-empty"><FlaskConical size={35}/><h2>{selected.status==='DRAFT'?'Deney gözden geçirmeye hazır':'Sonuç bekleniyor'}</h2><p>Snapshot sabitlendi. {selected.specification.optimization.algorithm==='genetic'?`${selected.specification.optimization.population} aday × ${selected.specification.optimization.generations} nesil`:'Seçilen modeller'} · {selected.specification.validation.method}.</p></section>)}
      {detailTab==='optimization'&&<OptimizationView generations={result?.optimization.generations||generations} result={result}/>}
      {detailTab==='features'&&(result?<section className="panel"><div className="panel-heading"><div><h2>Özellik kararlılığı</h2><p>Yalnızca geliştirme verisi · 4 kronolojik pencere · {result.feature_analysis.redundancy_pairs.length} yüksek korelasyonlu çift</p></div></div><div className="table-wrap"><table><thead><tr><th>Özellik</th><th>Seçildi</th><th>Spearman IC</th><th>Pencere IC</th><th>İşaret tutarlılığı</th><th>Mutual information</th></tr></thead><tbody>{result.feature_analysis.features.map(f=><tr key={f.feature}><td>{f.feature}</td><td>{result.selected_features.includes(f.feature)?<Check size={14}/>: '—'}</td><td>{fmt(f.ic,3)}</td><td>{f.rolling_ic.map(v=>fmt(v,2)).join(' / ')}</td><td>{percent(f.sign_consistency)}</td><td>{fmt(f.mutual_information,4)}</td></tr>)}</tbody></table></div></section>:<EmptyResult/>)}
      {detailTab==='validation'&&(result?<><section className="panel"><div className="panel-heading"><div><h2>Walk-forward / holdout kanıtı</h2><p>{result.split.development} geliştirme · {result.split.gap} sınır barı · {result.split.test} final test barı</p></div></div><div className="table-wrap"><table><thead><tr><th>Fold</th><th>Eğitim sonu (UTC)</th><th>Doğrulama başlangıcı</th><th>Gap</th><th>Sharpe</th></tr></thead><tbody>{result.optimization.best.folds.map((f,i)=><tr key={i}><td>{i+1}</td><td>{f.train_end.slice(0,16)}</td><td>{f.validation_start.slice(0,16)}</td><td>{f.gap_bars}</td><td>{fmt(f.sharpe)}</td></tr>)}</tbody></table></div></section><div className="inline-note">Klonlar aynı test dönemini yeniden ölçebilir. Tek deney içindeki optimizer izolasyonu, tüm araştırma geçmişinde hiç görülmemiş bir holdout garantisi değildir.</div><section className="panel"><div className="panel-heading"><div><h2>Maliyet ve kayma duyarlılığı</h2><p>Sabit test sinyalleri; bu rapor model seçimine geri beslenmez.</p></div></div><div className="table-wrap"><table><thead><tr><th>Çarpan</th><th>Toplam tek yön maliyeti</th><th>Getiri</th><th>Sharpe</th><th>Maks. düşüş</th></tr></thead><tbody>{result.cost_sensitivity.map(c=><tr key={c.cost_multiplier}><td>{c.cost_multiplier}×</td><td>{fmt(c.total_bps)} bp</td><td>{percent(c.return)}</td><td>{fmt(c.sharpe)}</td><td>{percent(c.max_drawdown)}</td></tr>)}</tbody></table></div></section></>:<EmptyResult/>)}
      {detailTab==='regimes'&&(result?<section className="panel"><div className="panel-heading"><div><h2>Test dönemi rejimleri</h2><p>HMM geliştirme döneminde öğrenir; durum etiketleri ekonomik rejim isimleri değildir.</p></div></div><div className="table-wrap"><table><thead><tr><th>Durum</th><th>Bar</th><th>Pay</th><th>Ortalama net bar getirisi</th></tr></thead><tbody>{result.regimes.map(r=><tr key={r.id}><td>S{r.id}</td><td>{r.bars}</td><td>{percent(r.share)}</td><td>{r.mean_net_return_bps===null?'—':`${fmt(r.mean_net_return_bps,3)} bp`}</td></tr>)}</tbody></table></div></section>:<EmptyResult/>)}
      {detailTab==='artifacts'&&<section className="panel artifact-panel"><h2>Deney specification</h2><div className="artifact-buttons">{['specification.json','frozen_candidate.json','model.joblib','result.json'].map(name=><button className="secondary" key={name} disabled={selected.status!=='COMPLETED'} onClick={()=>download(`/experiments/${selected.id}/artifacts/${name}`,name).catch(fail)}><ArrowDownToLine size={13}/>{name}</button>)}</div><pre>{JSON.stringify(selected.specification,null,2)}</pre><h2>Snapshot ve kaynak doğrulaması</h2><pre>{JSON.stringify(selected.snapshot,null,2)}</pre></section>}
      {detailTab==='logs'&&<section className="panel log-panel"><div className="panel-heading"><h2>Kalıcı event günlüğü</h2><span className="badge">{logs.length} olay</span></div><div className="logs">{logs.filter(l=>l.type!=='optimization.candidate.started').map(l=><div key={l.id}><time>{new Date(l.created_at).toLocaleTimeString('tr-TR')}</time><span>{l.type} · {String(l.payload.message||l.payload.status||`Nesil ${l.payload.generation||''}`)}</span></div>)}</div></section>}
    </>}
    {view==='compare'&&(comparison?<><section className="panel"><div className="panel-heading"><div><h2>Deney karşılaştırması</h2><p>Sermaye başlangıcı 100'e normalize edilir; tarihler UTC üzerinde hizalanır.</p></div></div>{comparison.warning&&<div className="alert">{comparison.warning}</div>}<EquityOverlay items={comparison.items} normalize/><div className="table-wrap"><table><thead><tr><th>Metrik</th>{comparison.items.map(i=><th key={i.experiment.id}>{i.experiment.code}</th>)}</tr></thead><tbody>{(['sharpe','return','max_drawdown','sortino'] as const).map(k=><tr key={k}><td>{k}</td>{comparison.items.map(i=><td key={i.experiment.id}>{['return','max_drawdown'].includes(k)?percent(i.result.metrics[k]):fmt(i.result.metrics[k])}</td>)}</tr>)}<tr><td>Validation → Test Sharpe farkı</td>{comparison.items.map(i=><td key={i.experiment.id}>{fmt(i.result.validation_test_sharpe_delta)}</td>)}</tr><tr><td>Model</td>{comparison.items.map(i=><td key={i.experiment.id}>{i.result.selected_model}</td>)}</tr><tr><td>Özellik sayısı</td>{comparison.items.map(i=><td key={i.experiment.id}>{i.result.selected_features.length}</td>)}</tr></tbody></table></div></section>{comparison.differences.map(d=><section key={d.code} className="panel artifact-panel spacing-top"><h2>{d.code} · ilk deneye göre farklar</h2><p>Eklenen: {d.features_added.join(', ')||'Yok'}</p><p>Çıkarılan: {d.features_removed.join(', ')||'Yok'}</p><pre>{JSON.stringify(d.config,null,2)}</pre></section>)}</>:<section className="panel big-empty"><GitCompareArrows size={35}/><h2>Deneyleri birlikte incele</h2><p>Deneyler ekranında tamamlanmış 2–5 kayıt seçip Karşılaştır düğmesini kullanın.</p></section>)}
    {view==='catalog'&&<><section className="panel artifact-panel"><h2>Çalışan yöntemler</h2><p>5 model adapter’ı · GA özellik/parametre seçimi · validation Sharpe/return hedefi · Pareto · feature survival · holdout/walk-forward · SSE · MCP.</p><div className="feature-tags">{models.map(m=><span key={m.id}>{m.name}</span>)}</div><h2>Veri veya sonraki geliştirme gerektirenler</h2>{capabilities?.unavailable.map(c=><div className="catalog-line" key={c.name}><span>{c.name}</span><span className="badge amber">{c.status==='requires_data'?'Harici veri gerekli':'Planlandı'}</span></div>)}<h2>REST / MCP</h2><p>REST: <a href="/docs" target="_blank" rel="noreferrer">OpenAPI belgeleri</a> · ortak contract: <a href="/api/v1/specification/schema" target="_blank" rel="noreferrer">Experiment Specification</a></p><pre>{'.venv\\Scripts\\python.exe -m backend.mcp.server'}</pre><p>MCP adapter aynı yerel REST servisine bağlanır. Önce uygulama sunucusunu başlatın. Doğal dil modeli bu sürümde bağlı değildir; MCP istemcisi schema üzerinden deney oluşturabilir.</p><h2>Hesaplama politikası</h2><pre>{JSON.stringify(capabilities?.policy,null,2)}</pre></section></>}
    {view==='activity'&&<section className="panel"><div className="panel-heading"><h2>REST / MCP işlem kaydı</h2></div><div className="table-wrap"><table><thead><tr><th>Zaman</th><th>Kaynak</th><th>İşlem</th><th>Deney</th></tr></thead><tbody>{activity.map(a=><tr key={a.id}><td>{new Date(a.created_at).toLocaleString('tr-TR')}</td><td>{a.source}</td><td>{a.operation}</td><td>{a.entity_id?.slice(0,8)||'—'}</td></tr>)}</tbody></table></div></section>}
    <dialog className="experiment-wizard" ref={dialog} onCancel={()=>setWizard(false)}><form onSubmit={e=>{e.preventDefault();if(step<5)setStep(step+1);else create();}}><div className="dialog-heading"><div><span className="eyebrow">EXPERIMENT SPECIFICATION · V1</span><h2>{editing?'Taslağı düzenle':'Yeni deney'}</h2></div><button type="button" className="icon-button" aria-label="Kapat" onClick={()=>setWizard(false)}><X size={20}/></button></div><div className="wizard-steps">{steps.map((s,i)=><span className={i===step?'current':i<step?'done':''} key={s}>{i+1}. {s}</span>)}</div>{error&&<div className="alert">{error}</div>}
    {step===0&&<><label>Deney adı<input required maxLength={120} value={spec.name} onChange={e=>setSpec({...spec,name:e.target.value})}/></label><label>Veri seti<select disabled={!!editing} value={spec.dataset_id} onChange={e=>setSpec({...spec,dataset_id:e.target.value})}>{datasets.map(d=><option key={d.id} value={d.id}>{d.name} {d.demo?'(sentetik)':''}</option>)}</select></label><label>Bar periyodu<select value={spec.timeframe} onChange={e=>setSpec({...spec,timeframe:e.target.value})}>{[['native','Kaynak periyodu'],['10min','10 dakika'],['1h','1 saat'],['4h','4 saat'],['1D','1 gün']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Açıklama<textarea value={spec.description} maxLength={2000} onChange={e=>setSpec({...spec,description:e.target.value})}/></label><p className="footnote">CSV yüklemek için sol menüdeki Veri merkezi ekranını kullanın. Yeni kayıt oluşturulduğunda snapshot alınır.</p></>}
    {step===1&&<><h3>Özellik havuzu</h3><p className="footnote">Elle seçim yapmazsanız {features.length} kullanılabilir özellikten seçim yapılır. Harici seriler her zaman bir bar gecikmeli hesaplanır.</p><div className="model-picker">{families.map(f=><label key={f.id}><input type="checkbox" checked={(spec.features.families||[]).includes(f.id)} onChange={()=>{const current=spec.features.families||[];setSpec({...spec,features:{...spec.features,families:current.includes(f.id)?current.filter(id=>id!==f.id):[...current,f.id]}})}}/><b>{f.name}</b><small>{f.description}{f.requires?` · ${f.requires}`:''}</small></label>)}</div><div className="feature-picker">{features.map(f=><label key={f.id}><input type="checkbox" checked={spec.features.names.includes(f.id)} onChange={()=>setSpec({...spec,features:{...spec.features,names:spec.features.names.includes(f.id)?spec.features.names.filter(n=>n!==f.id):[...spec.features.names,f.id]}})}/>{f.id}<small>{f.category}</small></label>)}</div><button type="button" className="text-button" onClick={()=>setSpec({...spec,features:{groups:['technical'],families:[],names:[]}})}>Tüm özellikleri kullan</button></>}
    {step===2&&<div className="model-picker">{models.map(m=><label key={m.id}><input type="checkbox" checked={spec.models.includes(m.id)} onChange={()=>setSpec({...spec,models:spec.models.includes(m.id)?spec.models.filter(n=>n!==m.id):[...spec.models,m.id]})}/><b>{m.name}</b><small>Getiri regresyonu · CPU</small></label>)}<p className="footnote">En iyi aday doğrulamada seçilir. Test yalnızca sabitlenen aday için açılır.</p></div>}
    {step===3&&<><label>Optimizer<select value={spec.optimization.algorithm} onChange={e=>setSpec({...spec,optimization:{...spec.optimization,algorithm:e.target.value}})}><option value="none">Sabit model karşılaştırması</option><option value="genetic">Genetik algoritma</option></select></label><div className="form-grid">{(['population','generations','min_features','max_features'] as const).map(k=><label key={k}>{({population:'Popülasyon',generations:'Nesil',min_features:'Minimum özellik',max_features:'Maksimum özellik'})[k]}<input type="number" min={k==='population'?4:1} max={k==='population'?32:k==='generations'?20:80} required value={spec.optimization[k]} onChange={e=>setSpec({...spec,optimization:{...spec.optimization,[k]:Number(e.target.value)}})}/></label>)}</div><label>Doğrulama hedefi<select value={spec.optimization.objective} onChange={e=>setSpec({...spec,optimization:{...spec.optimization,objective:e.target.value}})}><option value="sharpe">Sharpe maksimize et</option><option value="return">Getiri maksimize et</option></select></label><label>Maksimum doğrulama düşüşü (%)<input type="number" min="1" max="100" required value={spec.optimization.max_drawdown*100} onChange={e=>setSpec({...spec,optimization:{...spec.optimization,max_drawdown:Number(e.target.value)/100}})}/></label><p className="footnote">En fazla 128 aday, 10 dakika, tek worker. Aday sayısı: {spec.optimization.algorithm==='none'?spec.models.length:spec.optimization.population*spec.optimization.generations}.</p></>}
    {step===4&&<><div className="form-grid"><label>Doğrulama<select value={spec.validation.method} onChange={e=>setSpec({...spec,validation:{...spec.validation,method:e.target.value}})}><option value="walk_forward">Walk-forward (genişleyen pencere)</option><option value="holdout">Kronolojik holdout</option></select></label><label>Fold sayısı<input required type="number" min="2" max="5" value={spec.validation.folds} onChange={e=>setSpec({...spec,validation:{...spec.validation,folds:Number(e.target.value)}})}/></label><label>Eğitim oranı (%)<input required type="number" min="50" max="75" step="5" value={Math.round(spec.validation.train_ratio*100)} onChange={e=>setSpec({...spec,validation:{...spec.validation,train_ratio:Number(e.target.value)/100}})}/></label><label>Sınır aralığı (bar)<input required type="number" min="2" max="30" value={spec.validation.gap} onChange={e=>setSpec({...spec,validation:{...spec.validation,gap:Number(e.target.value)}})}/></label><label>İşlem maliyeti (bp)<input required type="number" min="0" max="20" step="0.1" value={spec.backtest.cost_bps} onChange={e=>setSpec({...spec,backtest:{...spec.backtest,cost_bps:Number(e.target.value)}})}/></label><label>Kayma (bp)<input required type="number" min="0" max="20" step="0.1" value={spec.backtest.slippage_bps} onChange={e=>setSpec({...spec,backtest:{...spec.backtest,slippage_bps:Number(e.target.value)}})}/></label><label>Sermaye (USD)<input required type="number" min="100" max="100000000" value={spec.backtest.capital} onChange={e=>setSpec({...spec,backtest:{...spec.backtest,capital:Number(e.target.value)}})}/></label><label>Rastgelelik tohumu<input required type="number" min="0" max="2147483647" value={spec.seed} onChange={e=>setSpec({...spec,seed:Number(e.target.value)})}/></label></div><div className="inline-note">Test %{fmt((.85-spec.validation.train_ratio)*100)} · optimizer erişimi kapalı. Walk-forward, test dışındaki geliştirme dönemini fold'lara böler.</div></>}
    {step===5&&<><div className="inline-note"><LockKeyhole size={17}/>Önce kalıcı taslak oluşturulur; çalıştırma deney ekranından ayrı olarak başlatılır.</div><pre className="spec-review">{JSON.stringify(spec,null,2)}</pre></>}
    <div className="wizard-footer"><button type="button" className="secondary" disabled={step===0} onClick={()=>setStep(step-1)}>Geri</button><span>{step+1} / {steps.length}</span><button type="submit" className="primary" disabled={busy||!stepValid}>{step===5?(busy?'Kaydediliyor…':'Taslağı kaydet'):'Devam'}<ArrowRight size={14}/></button></div></form></dialog>
  </div>;
}

function EmptyResult(){return <section className="panel small-empty">Bu analiz deney tamamlandığında kullanılabilir.</section>;}
function EquityOverlay({items,normalize=false}:{items:Comparison['items'];normalize?:boolean}){
  const [mode,setMode]=useState('equity');
  const mapping=new Map<string,Record<string,string|number>>();
  items.forEach((item,i)=>{const step=Math.max(1,Math.ceil(item.result.curve.length/600));item.result.curve.forEach((p,j)=>{if(j%step&&j!==item.result.curve.length-1)return;const row=mapping.get(p.timestamp)||{timestamp:p.timestamp};row[`value${i}`]=mode==='drawdown'?p.drawdown*100:normalize?p.equity/item.experiment.specification.backtest.capital*100:p.equity;mapping.set(p.timestamp,row);});});
  const points=[...mapping.values()].sort((a,b)=>String(a.timestamp).localeCompare(String(b.timestamp)));
  return <><div className="overlay-legend">{items.map((i,k)=><span key={i.experiment.id}><i style={{background:palette[k]}}/>{i.experiment.code}</span>)}<div className="segmented"><button onClick={()=>setMode('equity')} className={mode==='equity'?'chosen':''}>Sermaye</button><button onClick={()=>setMode('drawdown')} className={mode==='drawdown'?'chosen':''}>Düşüş</button></div></div><div className="research-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={points} margin={{right:22,bottom:10,left:8,top:20}}><CartesianGrid stroke="#27313f" strokeDasharray="3 5"/><XAxis dataKey="timestamp" minTickGap={90} tickFormatter={s=>s.slice(0,10)} tick={{fill:'#8797aa',fontSize:10}}/><YAxis domain={['auto','auto']} tickFormatter={v=>fmt(v,1)} tick={{fill:'#8797aa',fontSize:10}}/><Tooltip contentStyle={{background:'#172130',border:'1px solid #39475a'}}/>{items.map((i,k)=><Line key={i.experiment.id} name={i.experiment.code} dataKey={`value${k}`} stroke={palette[k]} dot={false} strokeWidth={2} connectNulls={false} isAnimationActive={false}/>)}</ComposedChart></ResponsiveContainer></div></>;
}
function OptimizationView({generations,result}:{generations:Generation[];result:Result|null}){
  const last=generations[generations.length-1];
  return <><section className="panel"><div className="panel-heading"><div><h2>Optimization Lab</h2><p>{last?`Nesil ${last.generation}/${last.total_generations} · ${last.candidate_count} benzersiz aday · çeşitlilik ${percent(last.diversity)}`:'GA nesilleri çalıştırma başladığında kaydedilir.'}</p></div></div>{generations.length>0&&<div className="research-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={generations}><CartesianGrid stroke="#27313f"/><XAxis dataKey="generation"/><YAxis domain={['auto','auto']}/><Tooltip contentStyle={{background:'#172130'}}/><Line dataKey="best_fitness" name="En iyi fitness" stroke="#55dfb0" dot={false}/><Line dataKey="mean_fitness" name="Ortalama fitness" stroke="#8b91f3" dot={false}/></ComposedChart></ResponsiveContainer></div>}{last&&<div className="inline-note">En iyi: {last.best.model} · {last.best.features.length} özellik · validation Sharpe {fmt(last.best.metrics.sharpe)} · getiri {percent(last.best.metrics.return)} · düşüş {percent(last.best.metrics.max_drawdown)}</div>}</section>{result&&<><div className="lower-grid"><section className="panel"><div className="panel-heading"><h2>Feature survival · en iyi %25 aday</h2></div><div className="survival-list">{[...result.optimization.survival].sort((a,b)=>b.top_survival-a.top_survival).map(s=><div className="weight-row" key={s.feature}><div><span>{s.feature}</span><b>{percent(s.top_survival)}</b></div><div className="weight-track"><span style={{width:`${s.top_survival*100}%`,background:'#55dfb0'}}/></div></div>)}</div></section><section className="panel"><div className="panel-heading"><div><h2>Pareto adayları</h2><p>{result.optimization.pareto.length} aday · Sharpe / getiri / düşüş</p></div></div><div className="research-chart"><ResponsiveContainer width="100%" height="100%"><ScatterChart><CartesianGrid stroke="#27313f"/><XAxis type="number" dataKey="return" name="Getiri" tickFormatter={percent}/><YAxis type="number" dataKey="sharpe" name="Sharpe"/><Tooltip contentStyle={{background:'#172130'}}/><Scatter data={result.optimization.pareto.map(c=>({...c.metrics,name:c.id}))} fill="#8b91f3"/></ScatterChart></ResponsiveContainer></div></section></div><section className="panel spacing-top"><div className="panel-heading"><h2>Değerlendirilen adaylar</h2></div><div className="table-wrap"><table><thead><tr><th>Aday</th><th>Model</th><th>Özellik</th><th>Val. Sharpe</th><th>Val. getiri</th><th>Val. düşüş</th><th>Sınır</th></tr></thead><tbody>{result.optimization.candidates.map(c=><tr key={c.id}><td>{c.id.slice(0,8)}</td><td>{c.model}</td><td>{c.features.length}</td><td>{fmt(c.metrics.sharpe)}</td><td>{percent(c.metrics.return)}</td><td>{percent(c.metrics.max_drawdown)}</td><td>{c.feasible?'Uygun':'Aşıldı'}</td></tr>)}</tbody></table></div></section></>}</>;
}
