import {useEffect,useRef,useState} from 'react';
import {ArrowDownToLine,ArrowRight,Check,Copy,FlaskConical,GitCompareArrows,LockKeyhole,Play,RefreshCw,Search,Square,X} from 'lucide-react';
import {CartesianGrid,ComposedChart,Line,ResponsiveContainer,Tooltip,XAxis,YAxis,Scatter,ScatterChart} from 'recharts';
import {request,download,defaultSpec,headers,terminal} from './platform-api';
import type {Spec,Experiment,Result,Comparison,Event,Generation} from './platform-api';
import type {Dataset} from './types';
import { useLang } from './i18n';
import { useWorkspace } from './workspace';
import './platform.css';

const palette=['#55dfb0','#8b91f3','#efb66c','#62b5ef','#e78fbe'];

export default function ResearchPlatform({newRequest}:{newRequest:number}){
  const { t, lang, fmt, locale } = useLang();
  const { currentId: wsId } = useWorkspace();
  const percent=(v:number)=>`${fmt(v*100)}%`;
  const stateLabel:Record<string,string>={DRAFT:t('rp.states.draft'),QUEUED:t('rp.states.queued'),DATA_PREPARATION:t('rp.states.prep'),FEATURE_ENGINEERING:t('rp.states.feat'),TRAINING:t('rp.states.train'),OPTIMIZING:t('rp.states.opt'),VALIDATING:t('rp.states.val'),TESTING:t('rp.states.test'),BACKTESTING:t('rp.states.bt'),ANALYZING:t('rp.states.analysis'),COMPLETED:t('rp.states.done'),FAILED:t('rp.states.fail'),CANCELLED:t('rp.states.cancel'),TIMEOUT:t('rp.states.timeout')};
  const initial=()=>structuredClone(defaultSpec);
  const [experiments,setExperiments]=useState<Experiment[]>([]),[selected,setSelected]=useState<Experiment|null>(null),[result,setResult]=useState<Result|null>(null);
  const [datasets,setDatasets]=useState<Dataset[]>([]),[features,setFeatures]=useState<{id:string;category:string}[]>([]),[models,setModels]=useState<{id:string;name:string}[]>([]);
  const [families,setFamilies]=useState<{id:string;name:string;description:string;requires?:string}[]>([]);
  const [capabilities,setCapabilities]=useState<{unavailable:{name:string;status:string}[];policy:Record<string,number>}|null>(null);
  const [view,setView]=useState('registry'),[detailTab,setDetailTab]=useState('overview'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState('');
  const [checked,setChecked]=useState<string[]>([]),[comparison,setComparison]=useState<Comparison|null>(null),[logs,setLogs]=useState<Event[]>([]),[generations,setGenerations]=useState<Generation[]>([]);
  const [wizard,setWizard]=useState(false),[step,setStep]=useState(0),[spec,setSpec]=useState<Spec>(initial),[editing,setEditing]=useState<string|null>(null),[tokenInput,setTokenInput]=useState('');
  const [activity,setActivity]=useState<{id:number;source:string;operation:string;entity_id:string;created_at:string}[]>([]);
  const [budget,setBudget]=useState<{usage:Record<string,number>;limits:Record<string,number>}|null>(null);
  const [ledger,setLedger]=useState<{id:number;experiment_id:string|null;event_type:string;quantity:number;details:Record<string,unknown>;created_at:string}[]>([]);
  const [seal,setSeal]=useState<{seal_id:string;epoch:number;access_count:number;invalidated_at:string|null;invalidation_reason:string|null}|null>(null);
  const dialog=useRef<HTMLDialogElement>(null),selectionRef=useRef<string|null>(null);
  const active=selected&&selected.status!=='DRAFT'&&!terminal(selected.status);
  const fail=(e:unknown)=>setError(e instanceof Error?e.message:String(e));
  async function refresh(){setExperiments(await request<Experiment[]>('/experiments'));}
  async function load(){try{const [es,ds,fs,ms,cs,fm]=await Promise.all([request<Experiment[]>('/experiments'),request<Dataset[]>('/datasets'),request<{id:string;category:string}[]>('/features'),request<{id:string;name:string}[]>('/models'),request<typeof capabilities>('/capabilities'),request<typeof families>('/feature-families')]);setExperiments(es);setDatasets(ds);setFeatures(fs);setModels(ms);setCapabilities(cs);setFamilies(fm);setError('');}catch(e){fail(e);}}
  useEffect(()=>{setSelected(null);setResult(null);setChecked([]);setComparison(null);load();},[wsId]);
  useEffect(()=>{if(wizard)request<{id:string;category:string}[]>(`/features?dataset_id=${encodeURIComponent(spec.dataset_id)}`).then(setFeatures).catch(fail);},[wizard,spec.dataset_id]);
  useEffect(()=>{if(newRequest){setSpec(initial());setEditing(null);setStep(0);setWizard(true);}},[newRequest]);
  useEffect(()=>{if(wizard&&!dialog.current?.open)dialog.current?.showModal();if(!wizard&&dialog.current?.open)dialog.current.close();},[wizard]);
  async function open(id:string){selectionRef.current=id;setResult(null);setSeal(null);try{const e=await request<Experiment>(`/experiments/${id}`);if(selectionRef.current!==id)return;setSelected(e);setView('detail');const records=await request<Event[]>(`/experiments/${id}/logs`);if(selectionRef.current!==id)return;setLogs(records);setGenerations(records.filter(r=>r.type==='optimization.generation.completed').map(r=>r.payload as unknown as Generation));try{const s=await request<typeof seal>(`/experiments/${id}/seal`);if(selectionRef.current===id)setSeal(s);}catch(se){fail(se);}if(e.status==='COMPLETED'){const r=await request<Result>(`/experiments/${id}/result`);if(selectionRef.current===id)setResult(r);}}catch(e){fail(e);}}
  useEffect(()=>{
    if(!selected||!active)return;
    const id=selected.id,controller=new AbortController();let cursor=0;
    async function listen(){
      try{
        const response=await fetch(`/api/v1/experiments/${id}/events?after=${cursor}`,{headers:headers(),signal:controller.signal});
        if(!response.ok||!response.body)throw new Error(t('rp.sseFail'));
        const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';
        while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let pos;
          while((pos=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,pos);buffer=buffer.slice(pos+2);const line=block.split('\n').find(l=>l.startsWith('data: '));
            if(line&&!block.includes('event: done')){const event=JSON.parse(line.slice(6)) as Event;cursor=event.id;
              setLogs(prev=>prev.some(e=>e.id===event.id)?prev:[...prev,event]);
              if(event.type==='optimization.generation.completed')setGenerations(prev=>prev.some(g=>g.generation===(event.payload as unknown as Generation).generation)?prev:[...prev,event.payload as unknown as Generation]);
              if(event.type==='experiment.status.changed'&&terminal(String(event.payload.status))){await open(id);await refresh();return;}
              if(event.type==='experiment.status.changed')setSelected(prev=>prev&&prev.id===id?{...prev,status:String(event.payload.status),run:prev.run?{...prev.run,status:String(event.payload.status),progress:Number(event.payload.progress||prev.run.progress),message:String(event.payload.message||prev.run.message)}:null}:prev);
            }
          }
        }
        if(!controller.signal.aborted){await open(id);await refresh();}
      }catch(e){if(!controller.signal.aborted)fail(e);}
    }
    listen();return()=>controller.abort();
  },[selected?.id,!!active]);
  async function perform(work:()=>Promise<void>){setBusy(true);setError('');try{await work();}catch(e){fail(e);}finally{setBusy(false);}}
  function sealOp(kind:'invalidate'|'rotate'){return ()=>{if(!selected)return;const reason=window.prompt(t('rp.reasonPrompt'),'');if(!reason)return;perform(async()=>{await request(`/experiments/${selected.id}/seal/${kind}`,'POST',{reason});await open(selected.id);});};}
  const evLabel=(k:string)=>{const v=t(`rp.ev.${k}`);return v===`rp.ev.${k}`?k:v;};
  function newExperiment(){setEditing(null);setSpec(initial());setStep(0);setWizard(true);}
  async function create(){await perform(async()=>{const e=await request<Experiment>(editing?`/experiments/${editing}`:'/experiments',editing?'PATCH':'POST',spec);setWizard(false);await refresh();await open(e.id);});}
  async function run(){if(!selected)return;await perform(async()=>{await request(`/experiments/${selected.id}/run`,'POST',undefined,{'Idempotency-Key':`web-${selected.id}`});await open(selected.id);await refresh();});}
  async function clone(){if(!selected)return;await perform(async()=>{const e=await request<Experiment>(`/experiments/${selected.id}/clone`,'POST',{name:selected.name.slice(0,100)+(lang==='en'?' · clone':' · klon')});await refresh();await open(e.id);setEditing(e.id);setSpec(e.specification);setStep(0);setWizard(true);});}
  async function compare(){await perform(async()=>{setComparison(await request<Comparison>('/experiments/compare','POST',{experiment_ids:checked}));setView('compare');});}
  const shown=experiments.filter(e=>(!statusFilter||e.status===statusFilter)&&(e.name+e.code+e.specification.models.join(' ')).toLowerCase().includes(query.toLowerCase()));
  const steps=[t('rp.stepData'),t('rp.stepFeat'),t('rp.stepModels'),t('rp.stepOpt'),t('rp.stepVal'),t('rp.stepReview')];
  const stepValid=step===0?!!spec.name.trim()&&!!spec.dataset_id:step===2?spec.models.length>0:step===3?spec.optimization.min_features<=spec.optimization.max_features&&spec.optimization.population*spec.optimization.generations<=128:true;
  return <div className="research-platform">
    <div className="research-toolbar"><div className="research-tabs">{[['registry',t('rp.experiments')],['budget',t('rp.budget')],['compare',t('rp.compare')],['catalog',t('rp.catalog')],['activity',t('rp.activity')]].map(([id,name])=><button className={view===id?'chosen':''} key={id} onClick={()=>{setView(id);if(id==='activity')request<typeof activity>('/activity').then(setActivity).catch(fail);if(id==='budget'){request('/research/budget').then(b=>setBudget(b as typeof budget)).catch(fail);request('/research/ledger?limit=200').then(l=>setLedger(l as typeof ledger)).catch(fail);}}}>{name}</button>)}</div><button className="text-button" onClick={()=>{load();if(selected)open(selected.id);}}><RefreshCw size={14}/>{t('rp.refresh')}</button></div>
    {error&&<div className="alert" role="alert">{error}<button aria-label={t('rp.close')} onClick={()=>setError('')}><X size={14}/></button></div>}
    {!capabilities&&<section className="panel research-auth"><p>{t('rp.apiKeyNote')}</p><label>{t('rp.apiKey')}<input type="password" value={tokenInput} onChange={e=>setTokenInput(e.target.value)}/></label><button className="secondary" onClick={()=>{sessionStorage.setItem('regimelab-token',tokenInput);load();}}>{t('rp.connect')}</button></section>}
    {view==='registry'&&<><div className="research-summary"><div><span>{t('rp.registry')}</span><b>{experiments.length}</b></div><div><span>{t('rp.completed')}</span><b>{experiments.filter(e=>e.status==='COMPLETED').length}</b></div><div><span>{t('rp.active')}</span><b>{experiments.filter(e=>e.status!=='DRAFT'&&!terminal(e.status)).length}</b></div><div><LockKeyhole size={19}/><span>{t('rp.testAccess')}</span><strong>{t('rp.afterSelection')}</strong></div></div><section className="panel"><div className="panel-heading"><div><h2>{t('rp.registryTitle')}</h2><p>{t('rp.registrySub')}</p></div><button className="secondary" onClick={newExperiment}>{t('rp.newExp')} <ArrowRight size={14}/></button></div><div className="research-filters"><label><Search size={14}/><input placeholder={t('rp.searchPh')} aria-label={t('rp.searchAria')} value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label={t('rp.filterAria')} value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">{t('rp.allStates')}</option>{Object.entries(stateLabel).map(([s,l])=><option value={s} key={s}>{l}</option>)}</select><button className="secondary" disabled={checked.length<2||busy} onClick={compare}><GitCompareArrows size={14}/>{t('rp.compareBtn')} ({checked.length}/5)</button></div><div className="table-wrap"><table><thead><tr><th/><th>{t('rp.colExp')}</th><th>{t('rp.colModels')}</th><th>{t('rp.colOpt')}</th><th>{t('rp.colSharpe')}</th><th>{t('rp.colStatus')}</th><th/></tr></thead><tbody>{shown.map(e=><tr key={e.id}><td><input type="checkbox" aria-label={`${e.code} ${t('rp.addCompare')}`} checked={checked.includes(e.id)} disabled={e.status!=='COMPLETED'||(!checked.includes(e.id)&&checked.length>=5)} onChange={()=>setChecked(prev=>prev.includes(e.id)?prev.filter(id=>id!==e.id):[...prev,e.id])}/></td><td><b>{e.name}</b><small className="table-subline">{e.code}{e.parent_id?' ← '+(experiments.find(p=>p.id===e.parent_id)?.code||e.parent_id.slice(0,8)):''}</small></td><td>{e.specification.models.join(', ')}</td><td>{e.specification.optimization.algorithm}</td><td>{fmt(e.run?.metrics?.sharpe)}</td><td><span className="badge">{stateLabel[e.status]||e.status}</span></td><td><button className="text-button" onClick={()=>open(e.id)}>{t('rp.inspect')} <ArrowRight size={13}/></button></td></tr>)}</tbody></table></div>{!shown.length&&<div className="small-empty"><FlaskConical size={30}/><span>{t('rp.emptyReg')}</span></div>}</section></>}
    {view==='budget'&&<><section className="panel"><div className="panel-heading"><div><h2>{t('rp.riskTitle')}</h2><p>{t('rp.riskSub')}</p></div>{budget&&<span className="badge">{t('rp.riskPressure')}: {percent(Math.max(0,...[['max_experiments','experiments'],['max_candidates','candidates'],['max_backtests','backtests'],['max_sealed_test_accesses','sealed_test_accesses']].map(([lim,use])=>(budget.usage[use]||0)/Math.max(1,budget.limits[lim]||1))))}</span>}</div>{budget?<div className="metrics-grid">{[['max_experiments','experiments',t('rp.exp')],['max_candidates','candidates',t('rp.candidates')],['max_backtests','backtests','Backtest'],['max_sealed_test_accesses','sealed_test_accesses',t('rp.sealedAccess')]].map(([lim,use,label])=>{const u=budget.usage[use]||0,l=budget.limits[lim]||1;return <div className="metric-card" key={lim}><div className="metric-label">{label}</div><div className="metric-value">{fmt(u,0)} / {fmt(l,0)}</div><div className="weight-track"><span style={{width:`${Math.min(100,u/l*100)}%`,background:u/l>=1?'#ef8f93':'#55dfb0'}}/></div></div>;})}</div>:<EmptyResult/>}</section><section className="panel spacing-top"><div className="panel-heading"><div><h2>{t('rp.ledger')}</h2></div><span className="badge">{ledger.length}</span></div>{ledger.length?<div className="table-wrap"><table><thead><tr><th>{t('rp.time')}</th><th>{t('rp.event')}</th><th>{t('rp.exp')}</th><th>{t('rp.qty')}</th><th>{t('rp.details')}</th></tr></thead><tbody>{ledger.map(l=><tr key={l.id}><td>{new Date(l.created_at).toLocaleString(locale)}</td><td>{evLabel(l.event_type)}</td><td>{l.experiment_id?.slice(0,8)||'—'}</td><td>{l.quantity}</td><td><small>{JSON.stringify(l.details||{}).slice(0,120)}</small></td></tr>)}</tbody></table></div>:<div className="small-empty"><span>{t('rp.ledgerEmpty')}</span></div>}</section></>}
    {view==='detail'&&selected&&<>
      <section className="panel experiment-banner"><div><span className="eyebrow">{selected.code}</span><h2>{selected.name}</h2><p>{selected.snapshot.details.name} · {fmt(selected.snapshot.details.rows,0)} bar · {selected.specification.models.join(' + ')}</p><code>SHA256 {selected.snapshot.sha256.slice(0,20)}…</code></div><div className="experiment-actions"><span className="badge">{stateLabel[selected.status]||selected.status}</span><button className="secondary" disabled={busy} onClick={clone}><Copy size={14}/>{t('rp.clone')}</button>{selected.status==='DRAFT'?<><button className="secondary" onClick={()=>{setEditing(selected.id);setSpec(selected.specification);setStep(0);setWizard(true);}}>{t('rp.edit')}</button><button className="primary" onClick={run} disabled={busy}><Play size={14}/>{t('rp.run')}</button></>:active?<button className="secondary" disabled={busy} onClick={()=>perform(async()=>{await request(`/experiments/${selected.id}/cancel`,'POST');await open(selected.id);})}><Square size={13}/>{t('rp.cancelExp')}</button>:null}</div></section>
      <div className="test-policy"><LockKeyhole size={14}/><b>{t('rp.testPolicy')}</b><span>{t('rp.testPolicySub')}</span>{seal&&<span className="badge">epoch {seal.epoch} · {seal.access_count}×{seal.invalidated_at?` · ${t('rp.sealBurned')}`:''}</span>}{seal&&!seal.invalidated_at&&<button className="text-button" disabled={busy} onClick={sealOp('invalidate')}>{t('rp.sealInvalidate')}</button>}{seal&&<button className="text-button" disabled={busy} onClick={sealOp('rotate')}>{t('rp.sealRotate')}</button>}</div>
      <div className="research-tabs detail-tabs">{[['overview',t('rp.tabResult')],['optimization',t('rp.tabOpt')],['features',t('rp.tabFeat')],['validation',t('rp.tabVal')],['regimes',t('rp.tabReg')],['artifacts',t('rp.tabArt')],['logs',t('rp.tabLogs')]].map(([id,l])=><button key={id} className={detailTab===id?'chosen':''} onClick={()=>setDetailTab(id)}>{l}</button>)}</div>
      {active&&<div className="running-bar"><span>{selected.run?.message}</span><b>{generations.length?`${t('rp.genLine')} ${generations[generations.length-1].generation}/${selected.specification.optimization.generations}`:`${selected.run?.progress||0}%`}</b><div className="progress-track"><span style={{width:`${selected.run?.progress||0}%`}}/></div></div>}
      {selected.run&&['FAILED','CANCELLED','TIMEOUT'].includes(selected.status)&&<div className="alert">{selected.run.message}</div>}
      {detailTab==='overview'&&(result?<><div className="metrics-grid">{[[t('rp.return'),percent(result.metrics.return)],[t('rp.sharpe'),fmt(result.metrics.sharpe)],[t('rp.maxdd'),percent(result.metrics.max_drawdown)],[t('rp.sortino'),fmt(result.metrics.sortino)]].map(([l,v])=><div className="metric-card" key={l}><div className="metric-label">{l}</div><div className="metric-value">{v}</div></div>)}</div><section className="panel"><div className="panel-heading"><div><h2>{result.selected_model} · {result.selected_features.length} {t('rp.features')}</h2><p>Validation Sharpe {fmt(result.validation_metrics.sharpe)} → Test Sharpe {fmt(result.metrics.sharpe)} · {t('rp.diff')} {fmt(result.validation_test_sharpe_delta)}</p></div><button className="text-button" onClick={()=>download(`/experiments/${selected.id}/export`,`${selected.code}.csv`).catch(fail)}><ArrowDownToLine size={14}/>CSV</button></div><EquityOverlay items={[{experiment:selected,result}]}/></section>{result.warnings.map(w=><div className="inline-note" key={w}>{w}</div>)}</>:<section className="panel big-empty"><FlaskConical size={35}/><h2>{selected.status==='DRAFT'?t('rp.readyDraft'):t('rp.awaiting')}</h2><p>{t('rp.snapshotLocked')} {selected.specification.optimization.algorithm==='genetic'?`${selected.specification.optimization.population} ${t('rp.candidates')} × ${selected.specification.optimization.generations} ${t('rp.generations')}`:t('rp.selModels')} · {selected.specification.validation.method}.</p></section>)}
      {detailTab==='optimization'&&<OptimizationView generations={result?.optimization.generations||generations} result={result}/>}
      {detailTab==='features'&&(result?<section className="panel"><div className="panel-heading"><div><h2>{t('rp.featStab')}</h2><p>{t('rp.featStabSub')} · {result.feature_analysis.redundancy_pairs.length} {t('rp.highCorr')}</p></div></div><div className="table-wrap"><table><thead><tr><th>{t('rp.colFeat')}</th><th>{t('rp.colSel')}</th><th>{t('rp.colIC')}</th><th>{t('rp.colWinIC')}</th><th>{t('rp.colSign')}</th><th>{t('rp.colMI')}</th></tr></thead><tbody>{result.feature_analysis.features.map(f=><tr key={f.feature}><td>{f.feature}</td><td>{result.selected_features.includes(f.feature)?<Check size={14}/>: '—'}</td><td>{fmt(f.ic,3)}</td><td>{f.rolling_ic.map(v=>fmt(v,2)).join(' / ')}</td><td>{percent(f.sign_consistency)}</td><td>{fmt(f.mutual_information,4)}</td></tr>)}</tbody></table></div></section>:<EmptyResult/>)}
      {detailTab==='validation'&&(result?<><section className="panel"><div className="panel-heading"><div><h2>Walk-forward / holdout {lang==='en'?'evidence':'kanıtı'}</h2><p>{result.split.development} {t('rp.dev')} · {result.split.gap} {t('rp.gapBar')} · {result.split.test} {t('rp.finalTest')}</p></div></div><div className="table-wrap"><table><thead><tr><th>{t('rp.fold')}</th><th>{t('rp.trainEnd')}</th><th>{t('rp.valStart')}</th><th>{t('rp.gap')}</th><th>{t('rp.sharpe')}</th></tr></thead><tbody>{result.optimization.best.folds.map((f,i)=><tr key={i}><td>{i+1}</td><td>{f.train_end.slice(0,16)}</td><td>{f.validation_start.slice(0,16)}</td><td>{f.gap_bars}</td><td>{fmt(f.sharpe)}</td></tr>)}</tbody></table></div></section><div className="inline-note">{t('rp.cloneNote')}</div><section className="panel"><div className="panel-heading"><div><h2>{t('rp.costTitle')}</h2><p>{t('rp.costSub')}</p></div></div><div className="table-wrap"><table><thead><tr><th>{t('rp.mult')}</th><th>{t('rp.oneWay')}</th><th>{t('rp.return')}</th><th>{t('rp.sharpe')}</th><th>{t('rp.maxdd')}</th></tr></thead><tbody>{result.cost_sensitivity.map(c=><tr key={c.cost_multiplier}><td>{c.cost_multiplier}×</td><td>{fmt(c.total_bps)} bp</td><td>{percent(c.return)}</td><td>{fmt(c.sharpe)}</td><td>{percent(c.max_drawdown)}</td></tr>)}</tbody></table></div></section></>:<EmptyResult/>)}
      {detailTab==='regimes'&&(result?<section className="panel"><div className="panel-heading"><div><h2>{t('rp.regTitle')}</h2><p>{t('rp.regSub')}</p></div></div><div className="table-wrap"><table><thead><tr><th>{t('rp.colState')}</th><th>{t('rp.colBar')}</th><th>{t('rp.colShare')}</th><th>{t('rp.colMean')}</th></tr></thead><tbody>{result.regimes.map(r=><tr key={r.id}><td>S{r.id}</td><td>{r.bars}</td><td>{percent(r.share)}</td><td>{r.mean_net_return_bps===null?'—':`${fmt(r.mean_net_return_bps,3)} bp`}</td></tr>)}</tbody></table></div></section>:<EmptyResult/>)}
      {detailTab==='artifacts'&&<section className="panel artifact-panel"><h2>{t('rp.spec')}</h2><div className="artifact-buttons">{['specification.json','frozen_candidate.json','model.joblib','result.json'].map(name=><button className="secondary" key={name} disabled={selected.status!=='COMPLETED'} onClick={()=>download(`/experiments/${selected.id}/artifacts/${name}`,name).catch(fail)}><ArrowDownToLine size={13}/>{name}</button>)}</div><pre>{JSON.stringify(selected.specification,null,2)}</pre><h2>{t('rp.snap')}</h2><pre>{JSON.stringify(selected.snapshot,null,2)}</pre></section>}
      {detailTab==='logs'&&<section className="panel log-panel"><div className="panel-heading"><h2>{t('rp.eventLog')}</h2><span className="badge">{logs.length} {t('rp.events')}</span></div><div className="logs">{logs.filter(l=>l.type!=='optimization.candidate.started').map(l=><div key={l.id}><time>{new Date(l.created_at).toLocaleTimeString(locale)}</time><span>{l.type} · {String((l.payload as Record<string,unknown>).message||(l.payload as Record<string,unknown>).status||`${t('rp.genLine')} ${(l.payload as Record<string,unknown>).generation||''}`)}</span></div>)}</div></section>}
    </>}
    {view==='compare'&&(comparison?<><section className="panel"><div className="panel-heading"><div><h2>{t('rp.cmpTitle')}</h2><p>{t('rp.cmpSub')}</p></div></div>{comparison.warning&&<div className="alert">{comparison.warning}</div>}<EquityOverlay items={comparison.items} normalize/><div className="table-wrap"><table><thead><tr><th>{t('rp.metric')}</th>{comparison.items.map(i=><th key={i.experiment.id}>{i.experiment.code}</th>)}</tr></thead><tbody>{(['sharpe','return','max_drawdown','sortino'] as const).map(k=><tr key={k}><td>{k}</td>{comparison.items.map(i=><td key={i.experiment.id}>{['return','max_drawdown'].includes(k)?percent(i.result.metrics[k]):fmt(i.result.metrics[k])}</td>)}</tr>)}<tr><td>{t('rp.valTestDiff')}</td>{comparison.items.map(i=><td key={i.experiment.id}>{fmt(i.result.validation_test_sharpe_delta)}</td>)}</tr><tr><td>{t('rp.model')}</td>{comparison.items.map(i=><td key={i.experiment.id}>{i.result.selected_model}</td>)}</tr><tr><td>{t('rp.featCount')}</td>{comparison.items.map(i=><td key={i.experiment.id}>{i.result.selected_features.length}</td>)}</tr></tbody></table></div></section>{comparison.differences.map(d=><section key={d.code} className="panel artifact-panel spacing-top"><h2>{d.code} · {t('rp.vsFirst')}</h2><p>{t('rp.added')}: {d.features_added.join(', ')||t('rp.none')}</p><p>{t('rp.removed')}: {d.features_removed.join(', ')||t('rp.none')}</p><pre>{JSON.stringify(d.config,null,2)}</pre></section>)}</>:<section className="panel big-empty"><GitCompareArrows size={35}/><h2>{t('rp.cmpEmpty')}</h2><p>{t('rp.cmpEmptySub')}</p></section>)}
    {view==='catalog'&&<><section className="panel artifact-panel"><h2>{t('rp.methods')}</h2><p>{t('rp.methodsSub')}</p><div className="feature-tags">{models.map(m=><span key={m.id}>{m.name}</span>)}</div><h2>{t('rp.needsData')}</h2>{capabilities?.unavailable.map(c=><div className="catalog-line" key={c.name}><span>{c.name}</span><span className="badge amber">{c.status==='requires_data'?t('rp.extData'):t('rp.planned')}</span></div>)}<h2>REST / MCP</h2><p>REST: <a href="/docs" target="_blank" rel="noreferrer">OpenAPI {lang==='en'?'docs':'belgeleri'}</a> · {lang==='en'?'shared contract':'ortak contract'}: <a href="/api/v1/specification/schema" target="_blank" rel="noreferrer">Experiment Specification</a></p><pre>{'.venv\\Scripts\\python.exe -m backend.mcp.server'}</pre><p>{lang==='en'?'The MCP adapter connects to the same local REST service. Start the app server first. No language model is attached in this version; an MCP client can create experiments via the schema.':'MCP adapter aynı yerel REST servisine bağlanır. Önce uygulama sunucusunu başlatın. Doğal dil modeli bu sürümde bağlı değildir; MCP istemcisi schema üzerinden deney oluşturabilir.'}</p><h2>{lang==='en'?'Compute policy':'Hesaplama politikası'}</h2><pre>{JSON.stringify(capabilities?.policy,null,2)}</pre></section></>}
    {view==='activity'&&<section className="panel"><div className="panel-heading"><h2>{t('rp.restexp')}</h2></div><div className="table-wrap"><table><thead><tr><th>{t('rp.time')}</th><th>{t('rp.source')}</th><th>{t('rp.op')}</th><th>{t('rp.exp')}</th></tr></thead><tbody>{activity.map(a=><tr key={a.id}><td>{new Date(a.created_at).toLocaleString(locale)}</td><td>{a.source}</td><td>{a.operation}</td><td>{a.entity_id?.slice(0,8)||'—'}</td></tr>)}</tbody></table></div></section>}
    <dialog className="experiment-wizard" ref={dialog} onCancel={()=>setWizard(false)}><form onSubmit={e=>{e.preventDefault();if(step<5)setStep(step+1);else create();}}><div className="dialog-heading"><div><span className="eyebrow">EXPERIMENT SPECIFICATION · V1</span><h2>{editing?t('rp.wizardEdit'):t('rp.wizardTitle')}</h2></div><button type="button" className="icon-button" aria-label={t('rp.close')} onClick={()=>setWizard(false)}><X size={20}/></button></div><div className="wizard-steps">{steps.map((s,i)=><span className={i===step?'current':i<step?'done':''} key={s}>{i+1}. {s}</span>)}</div>{error&&<div className="alert">{error}</div>}
    {step===0&&<><label>{t('rp.expName')}<input required maxLength={120} value={spec.name} onChange={e=>setSpec({...spec,name:e.target.value})}/></label><label>{t('rp.colExp')}<select disabled={!!editing} value={spec.dataset_id} onChange={e=>setSpec({...spec,dataset_id:e.target.value})}>{datasets.map(d=><option key={d.id} value={d.id}>{d.name} {d.demo?'(synthetic)':''}</option>)}</select></label><label>{t('rp.timeframe')}<select value={spec.timeframe} onChange={e=>setSpec({...spec,timeframe:e.target.value})}>{[['native',lang==='en'?'Native period':'Kaynak periyodu'],['10min',lang==='en'?'10 minutes':'10 dakika'],['1h',lang==='en'?'1 hour':'1 saat'],['4h',lang==='en'?'4 hours':'4 saat'],['1D',lang==='en'?'1 day':'1 gün']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>{t('rp.desc')}<textarea value={spec.description} maxLength={2000} onChange={e=>setSpec({...spec,description:e.target.value})}/></label><p className="footnote">{t('rp.csvNote')}</p></>}
    {step===1&&<><h3>{t('rp.pool')}</h3><p className="footnote">{t('rp.noManual')} {features.length} {t('rp.poolNote')}</p><div className="model-picker">{families.map(f=><label key={f.id}><input type="checkbox" checked={(spec.features.families||[]).includes(f.id)} onChange={()=>{const current=spec.features.families||[];setSpec({...spec,features:{...spec.features,families:current.includes(f.id)?current.filter(id=>id!==f.id):[...current,f.id]}})}}/><b>{f.name}</b><small>{f.description}{f.requires?` · ${f.requires}`:''}</small></label>)}</div><div className="feature-picker">{features.map(f=><label key={f.id}><input type="checkbox" checked={spec.features.names.includes(f.id)} onChange={()=>setSpec({...spec,features:{...spec.features,names:spec.features.names.includes(f.id)?spec.features.names.filter(n=>n!==f.id):[...spec.features.names,f.id]}})}/>{f.id}<small>{f.category}</small></label>)}</div><button type="button" className="text-button" onClick={()=>setSpec({...spec,features:{groups:['technical'],families:[],names:[]}})}>{t('rp.useAll')}</button></>}
    {step===2&&<div className="model-picker">{models.map(m=><label key={m.id}><input type="checkbox" checked={spec.models.includes(m.id)} onChange={()=>setSpec({...spec,models:spec.models.includes(m.id)?spec.models.filter(n=>n!==m.id):[...spec.models,m.id]})}/><b>{m.name}</b><small>{t('rp.retReg')}</small></label>)}<p className="footnote">{t('rp.bestVal')}</p></div>}
    {step===3&&<><label>{t('rp.optimizer')}<select value={spec.optimization.algorithm} onChange={e=>setSpec({...spec,optimization:{...spec.optimization,algorithm:e.target.value}})}><option value="none">{t('rp.fixedCmp')}</option><option value="genetic">{t('rp.genetic')}</option></select></label><div className="form-grid">{(['population','generations','min_features','max_features'] as const).map(k=><label key={k}>{({population:t('rp.pop'),generations:t('rp.gen'),min_features:t('rp.minF'),max_features:t('rp.maxF')})[k]}<input type="number" min={k==='population'?4:1} max={k==='population'?32:k==='generations'?20:80} required value={spec.optimization[k]} onChange={e=>setSpec({...spec,optimization:{...spec.optimization,[k]:Number(e.target.value)}})}/></label>)}</div><label>{t('rp.objective')}<select value={spec.optimization.objective} onChange={e=>setSpec({...spec,optimization:{...spec.optimization,objective:e.target.value}})}><option value="sharpe">{t('rp.maxSharpe')}</option><option value="return">{t('rp.maxRet')}</option></select></label><label>{t('rp.maxDdPct')}<input type="number" min="1" max="100" required value={spec.optimization.max_drawdown*100} onChange={e=>setSpec({...spec,optimization:{...spec.optimization,max_drawdown:Number(e.target.value)/100}})}/></label><p className="footnote">{t('rp.limits')} {spec.optimization.algorithm==='none'?spec.models.length:spec.optimization.population*spec.optimization.generations}.</p></>}
    {step===4&&<><div className="form-grid"><label>{t('rp.valMethod')}<select value={spec.validation.method} onChange={e=>setSpec({...spec,validation:{...spec.validation,method:e.target.value}})}><option value="walk_forward">{t('rp.wf')}</option><option value="holdout">{t('rp.holdout')}</option></select></label><label>{t('rp.folds')}<input required type="number" min="2" max="5" value={spec.validation.folds} onChange={e=>setSpec({...spec,validation:{...spec.validation,folds:Number(e.target.value)}})}/></label><label>{t('rp.trainPct')}<input required type="number" min="50" max="75" step="5" value={Math.round(spec.validation.train_ratio*100)} onChange={e=>setSpec({...spec,validation:{...spec.validation,train_ratio:Number(e.target.value)/100}})}/></label><label>{t('rp.gapBars')}<input required type="number" min="2" max="30" value={spec.validation.gap} onChange={e=>setSpec({...spec,validation:{...spec.validation,gap:Number(e.target.value)}})}/></label><label>{t('rp.costBp')}<input required type="number" min="0" max="20" step="0.1" value={spec.backtest.cost_bps} onChange={e=>setSpec({...spec,backtest:{...spec.backtest,cost_bps:Number(e.target.value)}})}/></label><label>{t('rp.slipBp')}<input required type="number" min="0" max="20" step="0.1" value={spec.backtest.slippage_bps} onChange={e=>setSpec({...spec,backtest:{...spec.backtest,slippage_bps:Number(e.target.value)}})}/></label><label>{t('rp.capUsd')}<input required type="number" min="100" max="100000000" value={spec.backtest.capital} onChange={e=>setSpec({...spec,backtest:{...spec.backtest,capital:Number(e.target.value)}})}/></label><label>{t('rp.seed')}<input required type="number" min="0" max="2147483647" value={spec.seed} onChange={e=>setSpec({...spec,seed:Number(e.target.value)})}/></label></div><div className="inline-note">Test %{fmt((.85-spec.validation.train_ratio)*100)} · {t('rp.closedOpt')}</div></>}
    {step===5&&<><div className="inline-note"><LockKeyhole size={17}/>{t('rp.lockNote')}</div><pre className="spec-review">{JSON.stringify(spec,null,2)}</pre></>}
    <div className="wizard-footer"><button type="button" className="secondary" disabled={step===0} onClick={()=>setStep(step-1)}>{t('rp.back')}</button><span>{step+1} / {steps.length}</span><button type="submit" className="primary" disabled={busy||!stepValid}>{step===5?(busy?t('rp.saving'):t('rp.saveDraft')):t('rp.next')}<ArrowRight size={14}/></button></div></form></dialog>
  </div>;
}

function EmptyResult(){
  const { t } = useLang();
  return <section className="panel small-empty">{t('rp.emptyAnalysis')}</section>;
}
function EquityOverlay({items,normalize=false}:{items:Comparison['items'];normalize?:boolean}){
  const { t, fmt } = useLang();
  const [mode,setMode]=useState('equity');
  const mapping=new Map<string,Record<string,string|number>>();
  items.forEach((item,i)=>{const step=Math.max(1,Math.ceil(item.result.curve.length/600));item.result.curve.forEach((p,j)=>{if(j%step&&j!==item.result.curve.length-1)return;const row=mapping.get(p.timestamp)||{timestamp:p.timestamp};row[`value${i}`]=mode==='drawdown'?p.drawdown*100:normalize?p.equity/item.experiment.specification.backtest.capital*100:p.equity;mapping.set(p.timestamp,row);});});
  const points=[...mapping.values()].sort((a,b)=>String(a.timestamp).localeCompare(String(b.timestamp)));
  return <><div className="overlay-legend">{items.map((i,k)=><span key={i.experiment.id}><i style={{background:palette[k]}}/>{i.experiment.code}</span>)}<div className="segmented"><button onClick={()=>setMode('equity')} className={mode==='equity'?'chosen':''}>{t('perf.equity')}</button><button onClick={()=>setMode('drawdown')} className={mode==='drawdown'?'chosen':''}>{t('perf.drawdown')}</button></div></div><div className="research-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={points} margin={{right:22,bottom:10,left:8,top:20}}><CartesianGrid stroke="#27313f" strokeDasharray="3 5"/><XAxis dataKey="timestamp" minTickGap={90} tickFormatter={s=>s.slice(0,10)} tick={{fill:'#8797aa',fontSize:10}}/><YAxis domain={['auto','auto']} tickFormatter={v=>fmt(v,1)} tick={{fill:'#8797aa',fontSize:10}}/><Tooltip contentStyle={{background:'#172130',border:'1px solid #39475a'}}/>{items.map((i,k)=><Line key={i.experiment.id} name={i.experiment.code} dataKey={`value${k}`} stroke={palette[k]} dot={false} strokeWidth={2} connectNulls={false} isAnimationActive={false}/>)}</ComposedChart></ResponsiveContainer></div></>;
}
function OptimizationView({generations,result}:{generations:Generation[];result:Result|null}){
  const { t, fmt } = useLang();
  const percent=(v:number)=>`${fmt(v*100)}%`;
  const last=generations[generations.length-1];
  return <><section className="panel"><div className="panel-heading"><div><h2>Optimization Lab</h2><p>{last?`${t('rp.genLine')} ${last.generation}/${last.total_generations} · ${last.candidate_count} ${t('rp.unique')} · ${t('rp.diversity')} ${percent(last.diversity)}`:t('rp.gaEmpty')}</p></div></div>{generations.length>0&&<div className="research-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={generations}><CartesianGrid stroke="#27313f"/><XAxis dataKey="generation"/><YAxis domain={['auto','auto']}/><Tooltip contentStyle={{background:'#172130'}}/><Line dataKey="best_fitness" name={t('rp.bestFitness')} stroke="#55dfb0" dot={false}/><Line dataKey="mean_fitness" name={t('rp.meanFitness')} stroke="#8b91f3" dot={false}/></ComposedChart></ResponsiveContainer></div>}{last&&<div className="inline-note">{t('rp.best')}: {last.best.model} · {last.best.features.length} {t('rp.features')} · validation Sharpe {fmt(last.best.metrics.sharpe)} · {t('rp.return').toLowerCase()} {percent(last.best.metrics.return)} · {t('rp.maxdd').toLowerCase()} {percent(last.best.metrics.max_drawdown)}</div>}</section>{result&&<><div className="lower-grid"><section className="panel"><div className="panel-heading"><h2>{t('rp.survival')}</h2></div><div className="survival-list">{[...result.optimization.survival].sort((a,b)=>b.top_survival-a.top_survival).map(s=><div className="weight-row" key={s.feature}><div><span>{s.feature}</span><b>{percent(s.top_survival)}</b></div><div className="weight-track"><span style={{width:`${s.top_survival*100}%`,background:'#55dfb0'}}/></div></div>)}</div></section><section className="panel"><div className="panel-heading"><div><h2>{t('rp.pareto')}</h2><p>{result.optimization.pareto.length} {t('rp.paretoSub')}</p></div></div><div className="research-chart"><ResponsiveContainer width="100%" height="100%"><ScatterChart><CartesianGrid stroke="#27313f"/><XAxis type="number" dataKey="return" name={t('rp.return')} tickFormatter={percent}/><YAxis type="number" dataKey="sharpe" name={t('rp.sharpe')}/><Tooltip contentStyle={{background:'#172130'}}/><Scatter data={result.optimization.pareto.map(c=>({...c.metrics,name:c.id}))} fill="#8b91f3"/></ScatterChart></ResponsiveContainer></div></section></div><section className="panel spacing-top"><div className="panel-heading"><h2>{t('rp.evaled')}</h2></div><div className="table-wrap"><table><thead><tr><th>{t('rp.colCand')}</th><th>{t('rp.colModel')}</th><th>{t('rp.colFeat')}</th><th>{t('rp.colValSh')}</th><th>{t('rp.colValRet')}</th><th>{t('rp.colValDd')}</th><th>{t('rp.colBound')}</th></tr></thead><tbody>{result.optimization.candidates.map(c=><tr key={c.id}><td>{c.id.slice(0,8)}</td><td>{c.model}</td><td>{c.features.length}</td><td>{fmt(c.metrics.sharpe)}</td><td>{percent(c.metrics.return)}</td><td>{percent(c.metrics.max_drawdown)}</td><td>{c.feasible?t('rp.feasible'):t('rp.exceeded')}</td></tr>)}</tbody></table></div></section></>}</>;
}
