import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { Presentation, PresentationFile } from '@oai/artifact-tool';

const skillDir = 'C:/Users/celik/.codex/plugins/cache/openai-primary-runtime/presentations/26.904.11930/skills/presentations';
const out = path.resolve('D:/agentic/ml/.deck-output/RegimeLab_Algosense_Ozellikler.pptx');
const { resolvePresentationFont } = await import(pathToFileURL(path.join(skillDir,'container_tools/artifact_tool_utils.mjs')).href);
const font = resolvePresentationFont();
const p = Presentation.create({ slideSize:{width:1280,height:720} });
const C={bg:'#081018',panel:'#101b25',green:'#00E5A0',text:'#F3F7FA',muted:'#91A4B6',line:'#203442',amber:'#F3BE67',red:'#F28F98',blue:'#75B9F2'};
function box(slide,text,x,y,w,h,size=18,color=C.text,bold=false){const s=slide.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});s.text=text;s.text.style={typeface:font,fontSize:size,bold,color,autoFit:'shrink'};return s;}
function base(title,kicker='REGIMELAB'){const s=p.slides.add();s.background.fill=C.bg;box(s,kicker,60,35,500,20,11,C.green,true);box(s,title,60,67,1160,54,31,C.text,true);box(s,'RegimeLab  |  Eylül 2026',60,682,400,16,10,C.muted,false);return s;}
function table(slide,rows,x,y,w,h,widths=[.27,.36,.15,.22]){const t=slide.tables.add({rows:rows.length,columns:4,left:x,top:y,width:w,height:h,values:rows,columnTracks:widths.map(v=>({mode:'fr',value:v}))});t.borders.assign({style:'solid',fill:C.line,width:1});for(let r=0;r<rows.length;r++){for(let c=0;c<4;c++){const cell=t.getCell(r,c);cell.text.style={typeface:font,fontSize:r===0?12:10,bold:r===0||c===0,color:r===0?C.bg:c===2?(String(rows[r][c]).includes('Var')?C.green:String(rows[r][c]).includes('Kısmen')?C.amber:C.red):C.text,autoFit:'shrink'};cell.fill=r===0?C.green:(r%2?C.panel:'#0C151E');}}return t;}
function notes(s){s.speakerNotes.textFrame.setText('Kaynak: RegimeLab proje kodu, README ve Algosense ana sayfasının görsel/iletişim yaklaşımı. https://algosense.com.tr/');}
let s=base('Algoritmik araştırma altyapısı','REGIMELAB × ALGOSENSE');box(s,'Program özellikleri, mevcut kapsam ve gelecek planı',60,155,690,42,22,C.muted);box(s,'Veriden modele, rejimden doğrulanmış backteste',60,250,650,70,34,C.text,true);box(s,'Koyu zemin · neon yeşil vurgu · düşük gecikme ve veri güveni odağı',60,350,650,24,14,C.green);box(s,'01',1060,580,120,70,54,C.green,true);notes(s);
s=base('Platformun çalışma modeli');const flow=['Piyasa verisi','PIT kontrolü','Feature üretimi','Rejim analizi','Model havuzu','Walk-forward','Final holdout'];flow.forEach((v,i)=>{const x=60+i*166;box(s,String(i+1).padStart(2,'0'),x,170,40,24,12,C.green,true);box(s,v,x,207,135,36,16,C.text,true);if(i<flow.length-1)box(s,'→',x+140,207,22,30,20,C.green,true)});box(s,'Temel omurga',60,330,240,22,14,C.green,true);box(s,'CSV veri sözleşmesi · snapshot + SHA-256 · Gaussian HMM · GA ile aday seçimi · maliyet duyarlı backtest · deney geçmişi',60,365,1030,70,23,C.text);box(s,'Amaç: araştırma kararlarını izlenebilir, kronolojik ve tekrarlanabilir hale getirmek.',60,500,950,30,16,C.muted);notes(s);
s=base('Data engineering ve FX / makro kapsamı');table(s,[['Özellik','Ne sağlar?','Durum','Gelecek planı'],['CSV + macro/fx/rates/cross-asset','Harici serileri ortak veri sözleşmesiyle alır','Var','Canlı sağlayıcı bağlantıları'],['Point-in-time / available_at','Yayın zamanından önce veriyi kullanmaz','Kısmen var','Vintage ve release calendar'],['Snapshot + SHA-256','Veri setini değişmez ve izlenebilir saklar','Var','Tam lineage'],['Vintage / revision / survivorship','Eski sürüm ve evren değişimini denetler','Yok','ALFRED + revision kayıtları'],['Option IV / forward / swaps / OIS','FX fiyatlama ve carry girdileri','Yok','Eğri ve surface pipeline'],['CFTC / dealer / order flow','Pozisyon ve mikro yapı sinyalleri','Yok','Tick ve order-book katmanı']],60,145,1160,430);notes(s);
s=base('Feature engineering ve stability');table(s,[['Özellik','Ne sağlar?','Durum','Gelecek planı'],['Lag / delta / return','Harici serilerden nedensel türevler üretir','Var','Feature registry'],['Rolling istatistikler','Volatilite, korelasyon, beta ve dağılım ölçüleri','Kısmen var','Quantile, MAD, IQR, entropy'],['Nonlinear transformations','Threshold, sigmoid, tanh, spline dönüşümleri','Yok','Versioned transformer’lar'],['IC / IC decay / sign consistency','Bilgi gücü ve zaman kararlılığını ölçer','Yok','Fold bazlı stability raporu'],['Orthogonalization / MI / clustering','Redundancy ve ortak bilgiyi azaltır','Yok','Train-only dönüşümler'],['PCA / PLS / factors / frac diff','Boyut indirgeme ve seri yapısı çıkarımı','Yok','Aday transformer modülleri'],['SHAP / ablation / regime stability','Katkıların rejimler arası dayanıklılığını test eder','Yok','Açıklama artifact’ları']],60,145,1160,445);notes(s);
s=base('Modelleme ve olasılıksal tahmin');table(s,[['Özellik','Ne sağlar?','Durum','Gelecek planı'],['Gaussian HMM','Piyasa rejimlerini ileri filtreleme ile çıkarır','Var','Daha geniş rejim modelleri'],['Ridge / Random Forest / HGBM','Trend, momentum ve volatilite uzmanları','Var','Kalibrasyon ve çeşitlilik'],['XGBoost / LightGBM','Gradient boosting tabanlı seçenekler','Var','Geniş HPO'],['Stacking / blending','Model havuzunu birleştirir','Kısmen var','Leakage kontrollü stacking'],['Probability calibration','Olasılık güvenilirliğini ölçer','Yok','Calibration pipeline'],['Conformal / uncertainty','Tahmin aralığı ve belirsizlik üretir','Yok','Conformal prediction'],['Quantile / distributional forecasting','Dağılım ve quantile tahmini yapar','Yok','Rejim bazlı tahmin']],60,145,1160,445);notes(s);
s=base('Validasyon, backtest ve yönetişim');table(s,[['Özellik','Ne sağlar?','Durum','Gelecek planı'],['Walk-forward + gap','Zaman sırasını koruyan doğrulama','Var','Daha ayrıntılı fold raporu'],['Untouched final holdout','Aday seçiminden sonra tek final test','Var','Test governance'],['Purged K-Fold / embargo / CPCV','Overlap ve leakage riskini azaltır','Yok','Gelişmiş splitter’lar'],['Rolling / anchored retraining','Modeli dönemsel yeniden eğitir','Yok','Retraining policy'],['Cost / slippage / latency sensitivity','Gerçekçilik ve dayanıklılık testi','Kısmen var','Stress matrix'],['Experiment registry / workspace','Deney, log, hash ve erişimi saklar','Var','Artifact lineage'],['SHAP / permutation stability','Açıklamaların kararlılığını ölçer','Yok','Stability raporu']],60,145,1160,445);notes(s);
s=base('Gelecek planı: veri güveninden üretim olasılıksallığına');const phases=[['01','Veri temeli','ALFRED vintage, release timestamp, timezone/DST ve missing-data provenance'],['02','Finansal veri','FX option IV, forward/swap, OIS, basis, CFTC ve order flow'],['03','Feature zekâsı','IC decay, stability selection, drift, structural break, SHAP ve ablation'],['04','İleri validasyon','Purged K-Fold, embargo, CPCV, rolling retraining ve nested selection'],['05','Tahmin katmanı','Calibration, conformal, quantile/distributional forecasting ve online learning']];phases.forEach((a,i)=>{const y=145+i*88;box(s,a[0],65,y,45,28,15,C.green,true);box(s,a[1],135,y,250,28,18,C.text,true);box(s,a[2],400,y,700,34,14,C.muted);if(i<4)box(s,'│',80,y+35,15,38,18,C.line)});box(s,'Öncelik sırası: veri doğruluğu → finansal gerçekçilik → feature stability → validasyon → belirsizlik yönetimi',60,610,1050,25,16,C.green,true);notes(s);

await fs.mkdir(path.dirname(out),{recursive:true});const file=await PresentationFile.exportPptx(p);await file.save(out);
